package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

var tierBadge = map[string]string{
	"stable": "🟢", "alpha": "🟡", "planned": "⬜", "missing": "❌", "negative": "🚫",
}

// taggedSorted returns the tagged entries sorted by (domain, symbol) for
// deterministic output.
func taggedSorted(entries []Entry) []Entry {
	var out []Entry
	for _, e := range entries {
		if e.HasCap {
			out = append(out, e)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Cap.Domain != out[j].Cap.Domain {
			return out[i].Cap.Domain < out[j].Cap.Domain
		}
		return out[i].Symbol < out[j].Symbol
	})
	return out
}

// renderJSON emits the queryable capability index (tagged entries only).
func renderJSON(entries []Entry) ([]byte, error) {
	b, err := json.MarshalIndent(taggedSorted(entries), "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// renderMarkdown emits the human-readable capability table grouped by domain.
func renderMarkdown(entries []Entry) []byte {
	t := taggedSorted(entries)
	var b strings.Builder
	b.WriteString("<!-- DO NOT EDIT — generated by cmd/capindex (`go generate ./...`). Source: aep:cap tags in internal/aep. -->\n")
	b.WriteString("# 能力表 (capabilities)\n\n")
	b.WriteString("徽章 tier:🟢stable · 🟡alpha · ⬜planned · ❌missing · 🚫negative　·　verify:none / roundtrip / ae-accept / render-pixel\n")
	b.WriteString(fmt.Sprintf("\n共 %d 条已标注能力。查询用 `go run ./cmd/capindex -q <词>` 或 grep `docs/capabilities.json`。\n", len(t)))
	cur := ""
	for _, e := range t {
		if e.Cap.Domain != cur {
			cur = e.Cap.Domain
			b.WriteString("\n## " + cur + "\n\n")
			b.WriteString("| 符号 | 状态 | verify | 需 AE ≥ | gate | 说明 |\n")
			b.WriteString("|---|---|---|---|---|---|\n")
		}
		sym := e.Symbol
		if e.Recv != "" {
			sym = e.Recv + "." + e.Symbol
		}
		desc := mdCell(e.Summary)
		if e.Cap.Boundary != "" {
			desc += " ⚠" + mdCell(e.Cap.Boundary)
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s%s | %s | %s | %s | %s |\n",
			sym, tierBadge[e.Cap.Tier], e.Cap.Tier, e.Cap.Verify, e.Cap.MinVer,
			mdCell(strings.Join(e.Cap.Gate, "<br>")), desc))
	}
	return []byte(b.String())
}

func mdCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
