"""Generate parameter name aliases from checked-in AE dictionaries.

Run from any directory: python internal/serializer/generate_effect_param_names.py
Only registered effect templates are included. Runtime resolution additionally
checks the actual effect's parameter definitions before accepting an alias.
"""
import json
from pathlib import Path
import re
import subprocess

here = Path(__file__).resolve().parent
root = here.parent.parent
registry = (here / 'mutate_effect_add.go').read_text(encoding='utf-8')
supported = set(re.findall(r'Effect\w+\s*=\s*"([^"]+)"', registry))
aliases = {}
for path in sorted((root / 'data/effects-dict').glob('effects_*.json')):
    data = json.loads(path.read_text(encoding='utf-8-sig'))
    for effect, definition in data['effects'].items():
        if effect not in supported:
            continue
        for match, param in definition['params'].items():
            name = param.get('name', '')
            if name and match.startswith(effect + '-'):
                aliases.setdefault(effect, {}).setdefault(match, set()).add(name)

quote = lambda value: json.dumps(value, ensure_ascii=False)
lines = [
    '// Code generated by generate_effect_param_names.py; DO NOT EDIT.',
    '// Source: data/effects-dict/effects_*.json (checked-in English/Chinese AE dictionaries).',
    'package serializer', '',
    'var effectParamNameAliases = map[string]map[string][]string{',
]
for effect, params in sorted(aliases.items()):
    lines.append(f'\t{quote(effect)}: {{')
    for match, names in sorted(params.items()):
        lines.append(f'\t\t{quote(match)}: {{{", ".join(map(quote, sorted(names)))}}},')
    lines.append('\t},')
lines.append('}')
out = here / 'effect_param_names_generated.go'
out.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
subprocess.run(['gofmt', '-w', str(out)], check=True)
print(f'Generated aliases for {len(aliases)} effects, {sum(map(len, aliases.values()))} parameters')
