// Code generated by a one-off alias generator script; hand-curated. DO NOT regenerate blindly.
// Package-level aliases re-exporting the scene runtime types/enums/constructors
// moved to internal/scene during the physical package split, so the aep public API + ~118 aep_test files
// keep compiling unchanged. aep imports scene.

package serializer

import "github.com/yueli-fx/aep-parser/internal/scene"

type (
	AECapabilities                  = scene.AECapabilities
	AEPropertyGroup                 = scene.AEPropertyGroup
	AETarget                        = scene.AETarget
	AVItem                          = scene.AVItem
	AutoOrientType                  = scene.AutoOrientType
	BezierPath                      = scene.BezierPath
	BitsPerChannel                  = scene.BitsPerChannel
	BlendingMode                    = scene.BlendingMode
	ColorManagementSystem           = scene.ColorManagementSystem
	Composition                     = scene.Composition
	CompositionWriter               = scene.CompositionWriter
	EGControllerType                = scene.EGControllerType
	Effect                          = scene.Effect
	EllipseNode                     = scene.EllipseNode
	EssentialGraphicsController     = scene.EssentialGraphicsController
	FeetFramesFilmType              = scene.FeetFramesFilmType
	FileSource                      = scene.FileSource
	FillNode                        = scene.FillNode
	FillRule                        = scene.FillRule
	Folder                          = scene.Folder
	Footage                         = scene.Footage
	FootageSource                   = scene.FootageSource
	FootageTimecodeDisplayStartType = scene.FootageTimecodeDisplayStartType
	FootageWriter                   = scene.FootageWriter
	FormatOptions                   = scene.FormatOptions
	FramesCountType                 = scene.FramesCountType
	GradientFillNode                = scene.GradientFillNode
	GradientKeyframe                = scene.GradientKeyframe
	GradientStrokeNode              = scene.GradientStrokeNode
	Guide                           = scene.Guide
	GuideOrientation                = scene.GuideOrientation
	InterpType                      = scene.InterpType
	ItemType                        = scene.ItemType
	ProjectItem                     = scene.ProjectItem
	JSONComposition                 = scene.JSONComposition
	JSONEGController                = scene.JSONEGController
	JSONEffect                      = scene.JSONEffect
	JSONFolder                      = scene.JSONFolder
	JSONFootage                     = scene.JSONFootage
	JSONFormatOptions               = scene.JSONFormatOptions
	JSONGuide                       = scene.JSONGuide
	JSONKeyframe                    = scene.JSONKeyframe
	JSONLayer                       = scene.JSONLayer
	JSONMarker                      = scene.JSONMarker
	JSONMask                        = scene.JSONMask
	JSONMaskPathKeyframe            = scene.JSONMaskPathKeyframe
	JSONMaskVertex                  = scene.JSONMaskVertex
	JSONOutputModule                = scene.JSONOutputModule
	JSONOutputModuleSettings        = scene.JSONOutputModuleSettings
	JSONProject                     = scene.JSONProject
	JSONProjectItem                 = scene.JSONProjectItem
	JSONProperty                    = scene.JSONProperty
	JSONRenderQueue                 = scene.JSONRenderQueue
	JSONRenderQueueItem             = scene.JSONRenderQueueItem
	JSONRenderSettings              = scene.JSONRenderSettings
	JSONShapePath                   = scene.JSONShapePath
	JSONShapePrimitive              = scene.JSONShapePrimitive
	JSONTemporalEase                = scene.JSONTemporalEase
	JSONTextParagraph               = scene.JSONTextParagraph
	JSONTextSource                  = scene.JSONTextSource
	JSONTextStyleRun                = scene.JSONTextStyleRun
	Keyframe                        = scene.Keyframe
	KeyframeWriter                  = scene.KeyframeWriter
	Layer                           = scene.Layer
	LayerQuality                    = scene.LayerQuality
	LayerTransform                  = scene.LayerTransform
	LayerType                       = scene.LayerType
	LayerWriter                     = scene.LayerWriter
	LightKind                       = scene.LightKind
	LightTypeID                     = scene.LightTypeID
	LutInterpolationMethod          = scene.LutInterpolationMethod
	Marker                          = scene.Marker
	MarkerSetRef                    = scene.MarkerSetRef
	MarkerWriter                    = scene.MarkerWriter
	Mask                            = scene.Mask
	MaskMode                        = scene.MaskMode
	MaskMotionBlurMode              = scene.MaskMotionBlurMode
	MaskFeatherFalloff              = scene.MaskFeatherFalloff
	MaskPathKey                     = scene.MaskPathKey
	MaskPathKeyframe                = scene.MaskPathKeyframe
	ScalarKeyframe                  = scene.ScalarKeyframe
	VectorKeyframe                  = scene.VectorKeyframe
	MaskVertex                      = scene.MaskVertex
	MaskWriter                      = scene.MaskWriter
	MaterialCastsShadowsMode        = scene.MaterialCastsShadowsMode
	OutputModule                    = scene.OutputModule
	OutputModuleSettings            = scene.OutputModuleSettings
	OutputModuleWriter              = scene.OutputModuleWriter
	PathNode                        = scene.PathNode
	PlaceholderSource               = scene.PlaceholderSource
	ParseWarning                    = scene.ParseWarning
	Project                         = scene.Project
	ProjectWriter                   = scene.ProjectWriter
	Property                        = scene.Property
	PropertyBase                    = scene.PropertyBase
	PropertyControlType             = scene.PropertyControlType
	PropertyGroup                   = scene.PropertyGroup
	PropertyGroupWriter             = scene.PropertyGroupWriter
	PropertyValueType               = scene.PropertyValueType
	PropertyWriter                  = scene.PropertyWriter
	RectNode                        = scene.RectNode
	RenderQueue                     = scene.RenderQueue
	RenderQueueItem                 = scene.RenderQueueItem
	RenderQueueItemWriter           = scene.RenderQueueItemWriter
	RenderQueueWriter               = scene.RenderQueueWriter
	RenderSettings                  = scene.RenderSettings
	ShapeBlendMode                  = scene.ShapeBlendMode
	ShapeCompositeOrder             = scene.ShapeCompositeOrder
	ShapeDirection                  = scene.ShapeDirection
	ShapeLayer                      = scene.ShapeLayer
	ShapeNode                       = scene.ShapeNode
	ShapeNodeKind                   = scene.ShapeNodeKind
	ShapePath                       = scene.ShapePath
	ShapePrimitive                  = scene.ShapePrimitive
	ShapePrimitiveKind              = scene.ShapePrimitiveKind
	SolidSource                     = scene.SolidSource
	StrokeDashes                    = scene.StrokeDashes
	StrokeLineCap                   = scene.StrokeLineCap
	StrokeLineJoin                  = scene.StrokeLineJoin
	MergePathsNode                  = scene.MergePathsNode
	OffsetPathsNode                 = scene.OffsetPathsNode
	RepeaterNode                    = scene.RepeaterNode
	RepeaterOrder                   = scene.RepeaterOrder
	RoundCornersNode                = scene.RoundCornersNode
	ZigZagNode                      = scene.ZigZagNode
	ZigZagPoints                    = scene.ZigZagPoints
	RoughenPoints                   = scene.RoughenPoints
	StarNode                        = scene.StarNode
	PuckerBloatNode                 = scene.PuckerBloatNode
	TwistNode                       = scene.TwistNode
	WigglePathsNode                 = scene.WigglePathsNode
	WiggleTransformNode             = scene.WiggleTransformNode
	StrokeNode                      = scene.StrokeNode
	TrimNode                        = scene.TrimNode
	TrimType                        = scene.TrimType
	StrokeTaper                     = scene.StrokeTaper
	StrokeWave                      = scene.StrokeWave
	TemporalEase                    = scene.TemporalEase
	TextAutoKernType                = scene.TextAutoKernType
	TextBaselineOption              = scene.TextBaselineOption
	TextCapsOption                  = scene.TextCapsOption
	TextDigitSet                    = scene.TextDigitSet
	TextJustification               = scene.TextJustification
	TextLeadingType                 = scene.TextLeadingType
	TextLineJoinType                = scene.TextLineJoinType
	TextParagraph                   = scene.TextParagraph
	TextParagraphDirection          = scene.TextParagraphDirection
	TextSource                      = scene.TextSource
	TextStyleRun                    = scene.TextStyleRun
	TimeDisplayType                 = scene.TimeDisplayType
	TrackMatteType                  = scene.TrackMatteType
	VectorGroup                     = scene.VectorGroup
)

const (
	AutoOrientAlongPath                           = scene.AutoOrientAlongPath
	AutoOrientCameraOrPointOfInterest             = scene.AutoOrientCameraOrPointOfInterest
	AutoOrientCharactersTowardCamera              = scene.AutoOrientCharactersTowardCamera
	AutoOrientNone                                = scene.AutoOrientNone
	BPC16                                         = scene.BPC16
	BPC32                                         = scene.BPC32
	BPC8                                          = scene.BPC8
	BlendingModeAdd                               = scene.BlendingModeAdd
	BlendingModeAlphaAdd                          = scene.BlendingModeAlphaAdd
	BlendingModeClassicColorBurn                  = scene.BlendingModeClassicColorBurn
	BlendingModeClassicColorDodge                 = scene.BlendingModeClassicColorDodge
	BlendingModeClassicDifference                 = scene.BlendingModeClassicDifference
	BlendingModeColor                             = scene.BlendingModeColor
	BlendingModeColorBurn                         = scene.BlendingModeColorBurn
	BlendingModeColorDodge                        = scene.BlendingModeColorDodge
	BlendingModeDarken                            = scene.BlendingModeDarken
	BlendingModeDarkerColor                       = scene.BlendingModeDarkerColor
	BlendingModeDifference                        = scene.BlendingModeDifference
	BlendingModeDissolve                          = scene.BlendingModeDissolve
	BlendingModeDivide                            = scene.BlendingModeDivide
	BlendingModeExclusion                         = scene.BlendingModeExclusion
	BlendingModeHardLight                         = scene.BlendingModeHardLight
	BlendingModeHardMix                           = scene.BlendingModeHardMix
	BlendingModeHue                               = scene.BlendingModeHue
	BlendingModeLighten                           = scene.BlendingModeLighten
	BlendingModeLighterColor                      = scene.BlendingModeLighterColor
	BlendingModeLinearBurn                        = scene.BlendingModeLinearBurn
	BlendingModeLinearDodge                       = scene.BlendingModeLinearDodge
	BlendingModeLinearLight                       = scene.BlendingModeLinearLight
	BlendingModeLuminescentPremul                 = scene.BlendingModeLuminescentPremul
	BlendingModeLuminosity                        = scene.BlendingModeLuminosity
	BlendingModeMultiply                          = scene.BlendingModeMultiply
	BlendingModeNormal                            = scene.BlendingModeNormal
	BlendingModeNormalCamera                      = scene.BlendingModeNormalCamera
	BlendingModeOverlay                           = scene.BlendingModeOverlay
	BlendingModePinLight                          = scene.BlendingModePinLight
	BlendingModeSaturation                        = scene.BlendingModeSaturation
	BlendingModeScreen                            = scene.BlendingModeScreen
	BlendingModeSilhouetteAlpha                   = scene.BlendingModeSilhouetteAlpha
	BlendingModeSilhouetteLuma                    = scene.BlendingModeSilhouetteLuma
	BlendingModeSoftLight                         = scene.BlendingModeSoftLight
	BlendingModeStencilAlpha                      = scene.BlendingModeStencilAlpha
	BlendingModeStencilLuma                       = scene.BlendingModeStencilLuma
	BlendingModeSubtract                          = scene.BlendingModeSubtract
	BlendingModeVividLight                        = scene.BlendingModeVividLight
	ColorManagementSystemAdobe                    = scene.ColorManagementSystemAdobe
	ColorManagementSystemOCIO                     = scene.ColorManagementSystemOCIO
	EGCheckbox                                    = scene.EGCheckbox
	EGColor                                       = scene.EGColor
	EGComment                                     = scene.EGComment
	EGDropdown                                    = scene.EGDropdown
	EGGroup                                       = scene.EGGroup
	EGMultiDimensional                            = scene.EGMultiDimensional
	EGPoint                                       = scene.EGPoint
	EGSlider                                      = scene.EGSlider
	EGText                                        = scene.EGText
	FeetFramesFilmTypeMM16                        = scene.FeetFramesFilmTypeMM16
	FeetFramesFilmTypeMM35                        = scene.FeetFramesFilmTypeMM35
	FillRuleEvenOdd                               = scene.FillRuleEvenOdd
	FillRuleNonzeroWinding                        = scene.FillRuleNonzeroWinding
	TrimTypeSimultaneously                        = scene.TrimTypeSimultaneously
	TrimTypeIndividually                          = scene.TrimTypeIndividually
	ZigZagPointsCorner                            = scene.ZigZagPointsCorner
	ZigZagPointsSmooth                            = scene.ZigZagPointsSmooth
	RoughenPointsCorner                           = scene.RoughenPointsCorner
	RoughenPointsSmooth                           = scene.RoughenPointsSmooth
	RepeaterOrderBelow                            = scene.RepeaterOrderBelow
	RepeaterOrderAbove                            = scene.RepeaterOrderAbove
	FootageTimecodeDisplayStartTypeStart0         = scene.FootageTimecodeDisplayStartTypeStart0
	FootageTimecodeDisplayStartTypeUseSourceMedia = scene.FootageTimecodeDisplayStartTypeUseSourceMedia
	FramesCountTypeStart0                         = scene.FramesCountTypeStart0
	FramesCountTypeStart1                         = scene.FramesCountTypeStart1
	FramesCountTypeTimecodeConversion             = scene.FramesCountTypeTimecodeConversion
	GuideHorizontal                               = scene.GuideHorizontal
	GuideVertical                                 = scene.GuideVertical
	InterpBezier                                  = scene.InterpBezier
	InterpHold                                    = scene.InterpHold
	InterpLinear                                  = scene.InterpLinear
	ItemTypeComposition                           = scene.ItemTypeComposition
	ItemTypeFolder                                = scene.ItemTypeFolder
	ItemTypeFootage                               = scene.ItemTypeFootage
	ItemTypeUnknown                               = scene.ItemTypeUnknown
	LayerQualityBest                              = scene.LayerQualityBest
	LayerQualityDraft                             = scene.LayerQualityDraft
	LayerQualityWireframe                         = scene.LayerQualityWireframe
	LayerType3DModel                              = scene.LayerType3DModel
	LayerTypeAV                                   = scene.LayerTypeAV
	LayerTypeAdjust                               = scene.LayerTypeAdjust
	LayerTypeCamera                               = scene.LayerTypeCamera
	LayerTypeLight                                = scene.LayerTypeLight
	LayerTypeNull                                 = scene.LayerTypeNull
	LayerTypeShape                                = scene.LayerTypeShape
	LayerTypeText                                 = scene.LayerTypeText
	LayerTypeUnknown                              = scene.LayerTypeUnknown
	LightKindAmbient                              = scene.LightKindAmbient
	LightKindParallel                             = scene.LightKindParallel
	LightKindPoint                                = scene.LightKindPoint
	LightKindSpot                                 = scene.LightKindSpot
	LightTypeAmbient                              = scene.LightTypeAmbient
	LightTypeParallel                             = scene.LightTypeParallel
	LightTypePoint                                = scene.LightTypePoint
	LightTypeSpot                                 = scene.LightTypeSpot
	LutInterpolationMethodTetrahedral             = scene.LutInterpolationMethodTetrahedral
	LutInterpolationMethodTrilinear               = scene.LutInterpolationMethodTrilinear
	MaskModeAdd                                   = scene.MaskModeAdd
	MaskModeDarken                                = scene.MaskModeDarken
	MaskModeDifference                            = scene.MaskModeDifference
	MaskModeIntersect                             = scene.MaskModeIntersect
	MaskModeLighten                               = scene.MaskModeLighten
	MaskModeNone                                  = scene.MaskModeNone
	MaskModeSubtract                              = scene.MaskModeSubtract
	MaskMotionBlurOff                             = scene.MaskMotionBlurOff
	MaskMotionBlurOn                              = scene.MaskMotionBlurOn
	MaskMotionBlurSameAsLayer                     = scene.MaskMotionBlurSameAsLayer
	MatchNameAnchorPoint                          = scene.MatchNameAnchorPoint
	MatchNameAudioLevels                          = scene.MatchNameAudioLevels
	MatchNameCameraAperture                       = scene.MatchNameCameraAperture
	MatchNameCameraBlurLevel                      = scene.MatchNameCameraBlurLevel
	MatchNameCameraDepthOfField                   = scene.MatchNameCameraDepthOfField
	MatchNameCameraFocusDistance                  = scene.MatchNameCameraFocusDistance
	MatchNameCameraIrisAspectRatio                = scene.MatchNameCameraIrisAspectRatio
	MatchNameCameraIrisDiffractionFringe          = scene.MatchNameCameraIrisDiffractionFringe
	MatchNameCameraIrisHighlightGain              = scene.MatchNameCameraIrisHighlightGain
	MatchNameCameraIrisHighlightSaturation        = scene.MatchNameCameraIrisHighlightSaturation
	MatchNameCameraIrisHighlightThreshold         = scene.MatchNameCameraIrisHighlightThreshold
	MatchNameCameraIrisRotation                   = scene.MatchNameCameraIrisRotation
	MatchNameCameraIrisRoundness                  = scene.MatchNameCameraIrisRoundness
	MatchNameCameraIrisShape                      = scene.MatchNameCameraIrisShape
	MatchNameCameraZoom                           = scene.MatchNameCameraZoom
	MatchNameEnvirAppear                          = scene.MatchNameEnvirAppear
	MatchNameGeometryBevelDirection               = scene.MatchNameGeometryBevelDirection
	MatchNameGeometryPlaneCurvature               = scene.MatchNameGeometryPlaneCurvature
	MatchNameGeometryPlaneSubdivision             = scene.MatchNameGeometryPlaneSubdivision
	MatchNameGroupAudio                           = scene.MatchNameGroupAudio
	MatchNameGroupCameraOptions                   = scene.MatchNameGroupCameraOptions
	MatchNameGroupEffectParade                    = scene.MatchNameGroupEffectParade
	MatchNameGroupGeometryOptions                 = scene.MatchNameGroupGeometryOptions
	MatchNameGroupLayerStyles                     = scene.MatchNameGroupLayerStyles
	MatchNameGroupLightOptions                    = scene.MatchNameGroupLightOptions
	MatchNameGroupMaskParade                      = scene.MatchNameGroupMaskParade
	MatchNameGroupMaterialOptions                 = scene.MatchNameGroupMaterialOptions
	MatchNameGroupShapeContents                   = scene.MatchNameGroupShapeContents
	MatchNameGroupTextProperties                  = scene.MatchNameGroupTextProperties
	MatchNameGroupTransform                       = scene.MatchNameGroupTransform
	MatchNameLightCastsShadows                    = scene.MatchNameLightCastsShadows
	MatchNameLightColor                           = scene.MatchNameLightColor
	MatchNameLightConeAngle                       = scene.MatchNameLightConeAngle
	MatchNameLightConeFeather                     = scene.MatchNameLightConeFeather
	MatchNameLightFalloffDistance                 = scene.MatchNameLightFalloffDistance
	MatchNameLightFalloffStart                    = scene.MatchNameLightFalloffStart
	MatchNameLightFalloffType                     = scene.MatchNameLightFalloffType
	MatchNameLightIntensity                       = scene.MatchNameLightIntensity
	MatchNameLightShadowDarkness                  = scene.MatchNameLightShadowDarkness
	MatchNameLightShadowDiffusion                 = scene.MatchNameLightShadowDiffusion
	MatchNameLightType                            = scene.MatchNameLightType
	MatchNameMaterialAcceptsLights                = scene.MatchNameMaterialAcceptsLights
	MatchNameMaterialAcceptsShadows               = scene.MatchNameMaterialAcceptsShadows
	MatchNameMaterialAmbient                      = scene.MatchNameMaterialAmbient
	MatchNameMaterialAppearsInRefl                = scene.MatchNameMaterialAppearsInRefl
	MatchNameMaterialCastsShadows                 = scene.MatchNameMaterialCastsShadows
	MatchNameMaterialDiffuse                      = scene.MatchNameMaterialDiffuse
	MatchNameMaterialFresnel                      = scene.MatchNameMaterialFresnel
	MatchNameMaterialGlossiness                   = scene.MatchNameMaterialGlossiness
	MatchNameMaterialIndexOfRefraction            = scene.MatchNameMaterialIndexOfRefraction
	MatchNameMaterialLightTransmission            = scene.MatchNameMaterialLightTransmission
	MatchNameMaterialMetal                        = scene.MatchNameMaterialMetal
	MatchNameMaterialReflection                   = scene.MatchNameMaterialReflection
	MatchNameMaterialShadowColor                  = scene.MatchNameMaterialShadowColor
	MatchNameMaterialShininess                    = scene.MatchNameMaterialShininess
	MatchNameMaterialSpecular                     = scene.MatchNameMaterialSpecular
	MatchNameMaterialTranspRolloff                = scene.MatchNameMaterialTranspRolloff
	MatchNameMaterialTransparency                 = scene.MatchNameMaterialTransparency
	MatchNameOpacity                              = scene.MatchNameOpacity
	MatchNameOrientation                          = scene.MatchNameOrientation
	MatchNamePosition                             = scene.MatchNamePosition
	MatchNamePosition0                            = scene.MatchNamePosition0
	MatchNamePosition1                            = scene.MatchNamePosition1
	MatchNamePosition2                            = scene.MatchNamePosition2
	MatchNameRotateX                              = scene.MatchNameRotateX
	MatchNameRotateY                              = scene.MatchNameRotateY
	MatchNameRotateZ                              = scene.MatchNameRotateZ
	MatchNameScale                                = scene.MatchNameScale
	MatchNameTimeRemap                            = scene.MatchNameTimeRemap
	MaterialCastsOff                              = scene.MaterialCastsOff
	MaterialCastsOn                               = scene.MaterialCastsOn
	MaterialCastsOnly                             = scene.MaterialCastsOnly
	PCTLAngle                                     = scene.PCTLAngle
	PCTLBoolean                                   = scene.PCTLBoolean
	PCTLColor                                     = scene.PCTLColor
	PCTLCurve                                     = scene.PCTLCurve
	PCTLEnum                                      = scene.PCTLEnum
	PCTLGroup                                     = scene.PCTLGroup
	PCTLInteger                                   = scene.PCTLInteger
	PCTLLayer                                     = scene.PCTLLayer
	PCTLMask                                      = scene.PCTLMask
	PCTLPaintGroup                                = scene.PCTLPaintGroup
	PCTLScalar                                    = scene.PCTLScalar
	PCTLSlider                                    = scene.PCTLSlider
	PCTLThreeD                                    = scene.PCTLThreeD
	PCTLTwoD                                      = scene.PCTLTwoD
	PCTLUnknown                                   = scene.PCTLUnknown
	PVTColor                                      = scene.PVTColor
	PVTNoValue                                    = scene.PVTNoValue
	PVTOneD                                       = scene.PVTOneD
	PVTThreeD                                     = scene.PVTThreeD
	PVTThreeDSpatial                              = scene.PVTThreeDSpatial
	PVTTwoD                                       = scene.PVTTwoD
	PVTTwoDSpatial                                = scene.PVTTwoDSpatial
	PVTUnknown                                    = scene.PVTUnknown
	ShapeBlendModeNormal                          = scene.ShapeBlendModeNormal
	ShapeCompositeOrderAbovePrevious              = scene.ShapeCompositeOrderAbovePrevious
	ShapeCompositeOrderBelowPrevious              = scene.ShapeCompositeOrderBelowPrevious
	ShapeDirectionNormal                          = scene.ShapeDirectionNormal
	ShapeDirectionReversed                        = scene.ShapeDirectionReversed
	ShapeKindEllipse                              = scene.ShapeKindEllipse
	ShapeKindFill                                 = scene.ShapeKindFill
	ShapeKindGradientFill                         = scene.ShapeKindGradientFill
	ShapeKindGradientStroke                       = scene.ShapeKindGradientStroke
	ShapeKindGroup                                = scene.ShapeKindGroup
	ShapeKindPath                                 = scene.ShapeKindPath
	ShapeKindRect                                 = scene.ShapeKindRect
	ShapeKindStroke                               = scene.ShapeKindStroke
	ShapeKindTrim                                 = scene.ShapeKindTrim
	ShapeKindRepeater                             = scene.ShapeKindRepeater
	ShapeKindRoundCorners                         = scene.ShapeKindRoundCorners
	ShapeKindOffsetPaths                          = scene.ShapeKindOffsetPaths
	ShapeKindMergePaths                           = scene.ShapeKindMergePaths
	ShapeKindZigZag                               = scene.ShapeKindZigZag
	ShapeKindStar                                 = scene.ShapeKindStar
	ShapeKindPuckerBloat                          = scene.ShapeKindPuckerBloat
	ShapeKindTwist                                = scene.ShapeKindTwist
	ShapeKindWigglePaths                          = scene.ShapeKindWigglePaths
	ShapeKindWiggleTransform                      = scene.ShapeKindWiggleTransform
	ShapePrimitiveEllipse                         = scene.ShapePrimitiveEllipse
	ShapePrimitiveRect                            = scene.ShapePrimitiveRect
	ShapePrimitiveStar                            = scene.ShapePrimitiveStar
	StrokeLineCapButt                             = scene.StrokeLineCapButt
	StrokeLineCapProjecting                       = scene.StrokeLineCapProjecting
	StrokeLineCapRound                            = scene.StrokeLineCapRound
	StrokeLineJoinBevel                           = scene.StrokeLineJoinBevel
	StrokeLineJoinMiter                           = scene.StrokeLineJoinMiter
	StrokeLineJoinRound                           = scene.StrokeLineJoinRound
	TargetAE2020                                  = scene.TargetAE2020
	TargetAE2021                                  = scene.TargetAE2021
	TargetAE2022                                  = scene.TargetAE2022
	TargetAE2023                                  = scene.TargetAE2023
	TargetAE2024                                  = scene.TargetAE2024
	TargetAE2025                                  = scene.TargetAE2025
	TextAutoKernMetric                            = scene.TextAutoKernMetric
	TextAutoKernNoAuto                            = scene.TextAutoKernNoAuto
	TextAutoKernOptical                           = scene.TextAutoKernOptical
	TextBaselineNormal                            = scene.TextBaselineNormal
	TextBaselineSubscript                         = scene.TextBaselineSubscript
	TextBaselineSuperscript                       = scene.TextBaselineSuperscript
	TextCapsAll                                   = scene.TextCapsAll
	TextCapsAllSmall                              = scene.TextCapsAllSmall
	TextCapsNormal                                = scene.TextCapsNormal
	TextCapsSmall                                 = scene.TextCapsSmall
	TextDigitSetArabic                            = scene.TextDigitSetArabic
	TextDigitSetArabicRTL                         = scene.TextDigitSetArabicRTL
	TextDigitSetDefault                           = scene.TextDigitSetDefault
	TextDigitSetFarsi                             = scene.TextDigitSetFarsi
	TextDigitSetHindi                             = scene.TextDigitSetHindi
	TextDirectionLeftToRight                      = scene.TextDirectionLeftToRight
	TextDirectionRightToLeft                      = scene.TextDirectionRightToLeft
	TextJustifyCenter                             = scene.TextJustifyCenter
	TextJustifyLeft                               = scene.TextJustifyLeft
	TextJustifyRight                              = scene.TextJustifyRight
	TextLeadingJapanese                           = scene.TextLeadingJapanese
	TextLeadingRoman                              = scene.TextLeadingRoman
	TextLineJoinBevel                             = scene.TextLineJoinBevel
	TextLineJoinMiter                             = scene.TextLineJoinMiter
	TextLineJoinRound                             = scene.TextLineJoinRound
	TimeDisplayTypeFrames                         = scene.TimeDisplayTypeFrames
	TimeDisplayTypeTimecode                       = scene.TimeDisplayTypeTimecode
	TrackMatteAlpha                               = scene.TrackMatteAlpha
	TrackMatteAlphaInverse                        = scene.TrackMatteAlphaInverse
	TrackMatteLuma                                = scene.TrackMatteLuma
	TrackMatteLumaInverse                         = scene.TrackMatteLumaInverse
	TrackMatteNone                                = scene.TrackMatteNone
)

// func re-exports (signatures mirror the pre-split aep funcs)

// Capabilities returns the AECapabilities matrix for the given AE target.
func Capabilities(target AETarget) AECapabilities { return scene.Capabilities(target) }

// NewEllipseNode returns a detached ellipse shape node.
func NewEllipseNode() *EllipseNode { return scene.NewEllipseNode() }

// NewFillNode returns a detached fill shape node.
func NewFillNode() *FillNode { return scene.NewFillNode() }

// NewGradientFillNode returns a detached gradient-fill shape node.
func NewGradientFillNode() *GradientFillNode { return scene.NewGradientFillNode() }

// NewGradientStrokeNode returns a detached gradient-stroke shape node.
func NewGradientStrokeNode() *GradientStrokeNode { return scene.NewGradientStrokeNode() }

// NewPathNode returns a detached path shape node.
func NewPathNode() *PathNode { return scene.NewPathNode() }

// NewRectNode returns a detached rectangle shape node.
func NewRectNode() *RectNode { return scene.NewRectNode() }

// NewOffsetPathsNode returns a detached Offset Paths filter node.
func NewOffsetPathsNode() *OffsetPathsNode { return scene.NewOffsetPathsNode() }

// NewTrimNode returns a detached Trim Paths filter node.
func NewTrimNode() *TrimNode { return scene.NewTrimNode() }

// NewStrokeNode returns a detached stroke shape node.
func NewStrokeNode() *StrokeNode { return scene.NewStrokeNode() }

// NewVectorGroup returns a detached vector group shape node.
func NewVectorGroup() *VectorGroup { return scene.NewVectorGroup() }

// TextEncodedByteLen returns the encoded byte length SetText would produce for s.
func TextEncodedByteLen(s string) int { return scene.TextEncodedByteLen(s) }

// WrapShapeLayer wraps a parsed shape Layer into a ShapeLayer view.
func WrapShapeLayer(layer *Layer) *ShapeLayer { return scene.WrapShapeLayer(layer) }
