package main

import (
	"os"
	"strings"
	"testing"
)

func TestGenerateFile_Golden(t *testing.T) {
	m, err := loadManifest("./testdata/manifest_sample.json")
	if err != nil {
		t.Fatal(err)
	}
	got, err := generateFile(m, m.Files[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(got, "<!-- Code generated by docgen") {
		t.Fatalf("missing version header: %q", got[:60])
	}
	want, err := os.ReadFile("./testdata/golden/sample_file.md")
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		t.Fatalf("mismatch:\n--- got ---\n%s", got)
	}
}

func TestValidateAnnotations_RealTree(t *testing.T) {
	dirs := []string{
		"../../internal/aep", "../../internal/scene", "../../internal/codec",
	}
	lps, err := loadPackages(dirs)
	if err != nil {
		t.Fatal(err)
	}
	if errs := validateAnnotations(lps); len(errs) != 0 {
		for _, e := range errs {
			t.Errorf("docgen self-validate: %v", e)
		}
	}
}
