package main

//go:generate go run . -manifest ../../docs/docgen.json

import (
	"flag"
	"fmt"
	"os"
	"runtime"
	"strings"
)

func main() {
	mf := flag.String("manifest", "docs/docgen.json", "manifest path")
	flag.Parse()
	m, err := loadManifest(*mf)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
	for _, fm := range m.Files {
		out, err := generateFile(m, fm)
		if err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
		dst := m.resolve(fm.Out)
		if err := os.WriteFile(dst, []byte(out), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
		fmt.Println("docgen: wrote", dst)
	}
	if m.Index != "" {
		idx, err := buildIndex(m)
		if err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
		dst := m.resolve(m.Index)
		if err := os.WriteFile(dst, []byte(idx), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
		fmt.Println("docgen: wrote", dst)
	}
}

// generateFile 渲一个输出文件：version header + head include + 各 root type + tail include。
// 跨 manifest 的所有包扫描（M8 多包：facade aep + scene + codec），类型取真定义、
// 自由函数取 facade re-export。
func generateFile(m *manifest, fm fileManifest) (string, error) {
	dirs := m.pkgDirs()
	lps, err := loadPackages(dirs)
	if err != nil {
		return "", err
	}
	if errs := validateAnnotations(lps); len(errs) > 0 {
		var sb strings.Builder
		for _, e := range errs {
			fmt.Fprintf(&sb, "  %v\n", e)
		}
		return "", fmt.Errorf("annotation validation failed before writing:\n%s", sb.String())
	}
	types := withMethodsMulti(extractTypesMulti(lps), lps)
	for _, d := range dirs {
		attachExamples(types, d)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- Code generated by docgen; DO NOT EDIT. %s -->\n", runtime.Version())
	if fm.Head != "" {
		h, err := os.ReadFile(m.resolve(fm.Head))
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\n%s\n", strings.TrimSpace(string(h)))
	}
	for _, root := range fm.Roots {
		dt := findType(types, root)
		if dt == nil {
			return "", fmt.Errorf("root type %q not found in %v", root, dirs)
		}
		b.WriteString("\n")
		b.WriteString(renderType(dt))
	}
	if len(fm.Funcs) > 0 {
		funcs, err := extractPackageFuncsMulti(lps, fm.Funcs)
		if err != nil {
			return "", err
		}
		b.WriteString("\n")
		b.WriteString(renderFuncs(funcs))
	}
	if fm.Tail != "" {
		tl, err := os.ReadFile(m.resolve(fm.Tail))
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\n%s\n", strings.TrimSpace(string(tl)))
	}
	return b.String(), nil
}
