package main

import (
	"flag"
	"fmt"
	"os"
	"runtime"
	"strings"
)

func main() {
	mf := flag.String("manifest", "docs/docgen.json", "manifest path")
	flag.Parse()
	m, err := loadManifest(*mf)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
	for _, fm := range m.Files {
		out, err := generateFile(m, fm)
		if err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
		dst := m.resolve(fm.Out)
		if err := os.WriteFile(dst, []byte(out), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
		fmt.Println("docgen: wrote", dst)
	}
}

// generateFile 渲一个输出文件：version header + head include + 各 root type + tail include。
func generateFile(m *manifest, fm fileManifest) (string, error) {
	pkgDir := m.resolve(m.Pkg)
	lp, err := loadPackage(pkgDir)
	if err != nil {
		return "", err
	}
	types := withMethods(extractTypes(lp), lp)
	attachExamples(types, pkgDir)

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- Code generated by docgen; DO NOT EDIT. %s -->\n", runtime.Version())
	if fm.Head != "" {
		h, err := os.ReadFile(m.resolve(fm.Head))
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\n%s\n", strings.TrimSpace(string(h)))
	}
	for _, root := range fm.Roots {
		dt := findType(types, root)
		if dt == nil {
			return "", fmt.Errorf("root type %q not found in %s", root, pkgDir)
		}
		b.WriteString("\n")
		b.WriteString(renderType(dt))
	}
	if fm.Tail != "" {
		tl, err := os.ReadFile(m.resolve(fm.Tail))
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\n%s\n", strings.TrimSpace(string(tl)))
	}
	return b.String(), nil
}
