package main

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// Generated references describe source APIs, not the Go binary that generated
// them. Toolchain patch upgrades must not invalidate the checked-in artifacts.
func TestGeneratedArtifactsOmitToolchainVersion(t *testing.T) {
	m, err := loadManifest("./testdata/manifest_sample.json")
	if err != nil {
		t.Fatal(err)
	}
	doc, err := generateFile(m, m.Files[0])
	if err != nil {
		t.Fatal(err)
	}
	if header := strings.SplitN(doc, "\n", 2)[0]; header != "<!-- Code generated by docgen; DO NOT EDIT. -->" {
		t.Errorf("toolchain-dependent markdown header: %s", header)
	}
	index, err := buildIndex(m)
	if err != nil {
		t.Fatal(err)
	}
	var metadata map[string]json.RawMessage
	if err := json.Unmarshal([]byte(index), &metadata); err != nil {
		t.Fatal(err)
	}
	if _, present := metadata["go_version"]; present {
		t.Error("generated index includes the build toolchain version")
	}
}

func TestGenerateFile_Golden(t *testing.T) {
	m, err := loadManifest("./testdata/manifest_sample.json")
	if err != nil {
		t.Fatal(err)
	}
	got, err := generateFile(m, m.Files[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(got, "<!-- Code generated by docgen") {
		t.Fatalf("missing version header: %q", got[:60])
	}
	want, err := os.ReadFile("./testdata/golden/sample_file.md")
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		t.Fatalf("mismatch:\n--- got ---\n%s", got)
	}
}

func TestValidateAnnotations_RealTree(t *testing.T) {
	dirs := []string{
		"../../internal/aep", "../../internal/scene", "../../internal/codec",
	}
	lps, err := loadPackages(dirs)
	if err != nil {
		t.Fatal(err)
	}
	if errs := validateAnnotations(lps); len(errs) != 0 {
		for _, e := range errs {
			t.Errorf("docgen self-validate: %v", e)
		}
	}
}
