package scene

// unitsTextMap maps property match-names to their unit strings.
// Ported from py-aep data/units.py. Used by Property.UnitsText().
var unitsTextMap = map[string]string{
	"ADBE Ambient Coefficient":            "percent",
	"ADBE Anchor Point":                   "pixels",
	"ADBE Audio Levels":                   "dB",
	"ADBE Camera Aperture":                "pixels",
	"ADBE Camera Blur Level":              "percent",
	"ADBE Camera Focus Distance":          "pixels",
	"ADBE Camera Zoom":                    "pixels",
	"ADBE Cartoonify-0012":                "percent",
	"ADBE Diffuse Coefficient":            "percent",
	"ADBE Drop Shadow-0002":               "percent",
	"ADBE Drop Shadow-0003":               "degrees",
	"ADBE Effect Mask Opacity":            "percent",
	"ADBE Emboss-0001":                    "degrees",
	"ADBE Emboss-0004":                    "percent",
	"ADBE Fill-0005":                      "percent",
	"ADBE FreePin3 PosPin Position":       "pixels",
	"ADBE FreePin3 PosPin Rotation":       "degrees",
	"ADBE FreePin3 PosPin Scale":          "percent",
	"ADBE FreePin3 PosPin Vtx Offset":     "pixels",
	"ADBE Fresnel Coefficient":            "percent",
	"ADBE Geometry2-0001":                 "pixels",
	"ADBE Geometry2-0002":                 "pixels",
	"ADBE Geometry2-0006":                 "degrees",
	"ADBE Geometry2-0007":                 "degrees",
	"ADBE Glo2-0002":                      "percent",
	"ADBE Glo2-0009":                      "percent",
	"ADBE Glo2-0010":                      "degrees",
	"ADBE Glo2-0011":                      "percent",
	"ADBE Global Altitude2":               "degrees",
	"ADBE Global Angle2":                  "degrees",
	"ADBE Glossiness Coefficient":         "percent",
	"ADBE HUE SATURATION-0004":            "degrees",
	"ADBE HUE SATURATION-0005":            "pixels",
	"ADBE HUE SATURATION-0006":            "pixels",
	"ADBE HUE SATURATION-0008":            "degrees",
	"ADBE HUE SATURATION-0010":            "pixels",
	"ADBE Hole Bevel Depth":               "percent",
	"ADBE Invert-0002":                    "percent",
	"ADBE Iris Rotation":                  "degrees",
	"ADBE Iris Roundness":                 "percent",
	"ADBE Layer Fill Opacity2":            "percent",
	"ADBE Lens Flare-0001":                "pixels",
	"ADBE Lens Flare-0002":                "percent",
	"ADBE Lens Flare-0003":                "percent",
	"ADBE Light Backgd Blur":              "percent",
	"ADBE Light Backgd Opacity":           "percent",
	"ADBE Light Cone Angle":               "degrees",
	"ADBE Light Cone Feather 2":           "percent",
	"ADBE Light Intensity":                "percent",
	"ADBE Light Shadow Darkness":          "percent",
	"ADBE Light Shadow Diffusion":         "pixels",
	"ADBE Light Transmission":             "percent",
	"ADBE Mask Feather":                   "pixels",
	"ADBE Mask Offset":                    "pixels",
	"ADBE Mask Opacity":                   "percent",
	"ADBE Metal Coefficient":              "percent",
	"ADBE Noise Alpha2-0002":              "percent",
	"ADBE Noise Alpha2-0005":              "degrees",
	"ADBE Opacity":                        "percent",
	"ADBE Orientation":                    "degrees",
	"ADBE Paint Anchor Point":             "pixels",
	"ADBE Paint Angle":                    "degrees",
	"ADBE Paint Begin":                    "percent",
	"ADBE Paint Clone Position":           "pixels",
	"ADBE Paint End":                      "percent",
	"ADBE Paint Flow":                     "percent",
	"ADBE Paint Hardness":                 "percent",
	"ADBE Paint Opacity":                  "percent",
	"ADBE Paint Position":                 "pixels",
	"ADBE Paint Rotation":                 "degrees",
	"ADBE Paint Roundness":                "percent",
	"ADBE Paint Scale":                    "percent",
	"ADBE Paint Tip Spacing":              "percent",
	"ADBE Plane Curvature":                "percent",
	"ADBE Position":                       "pixels",
	"ADBE Position_0":                     "pixels",
	"ADBE Position_1":                     "pixels",
	"ADBE Position_2":                     "pixels",
	"ADBE Reflection Coefficient":         "percent",
	"ADBE Rotate X":                       "degrees",
	"ADBE Rotate Y":                       "degrees",
	"ADBE Rotate Z":                       "degrees",
	"ADBE Roughen Edges-0006":             "pixels",
	"ADBE Roughen Edges-0007":             "pixels",
	"ADBE Roughen Edges-0009":             "degrees",
	"ADBE Scale":                          "percent",
	"ADBE Shininess Coefficient":          "percent",
	"ADBE Simple Choker-0002":             "pixels",
	"ADBE Specular Coefficient":           "percent",
	"ADBE Text Anchor Point Align":        "percent",
	"ADBE Time Remapping":                 "seconds",
	"ADBE Tint-0003":                      "percent",
	"ADBE Transp Rolloff":                 "percent",
	"ADBE Transparency Coefficient":       "percent",
	"ADBE Turbulent Displace-0004":        "pixels",
	"ADBE Turbulent Displace-0005":        "percent",
	"ADBE Turbulent Displace-0006":        "degrees",
	"ADBE Vec3D Back Ambient":             "percent",
	"ADBE Vec3D Back Diffuse":             "percent",
	"ADBE Vec3D Back Fresnel":             "percent",
	"ADBE Vec3D Back Gloss":               "percent",
	"ADBE Vec3D Back Metal":               "percent",
	"ADBE Vec3D Back Reflection":          "percent",
	"ADBE Vec3D Back Shininess":           "percent",
	"ADBE Vec3D Back Specular":            "percent",
	"ADBE Vec3D Back XparRoll":            "percent",
	"ADBE Vec3D Back Xparency":            "percent",
	"ADBE Vec3D Bevel Ambient":            "percent",
	"ADBE Vec3D Bevel Diffuse":            "percent",
	"ADBE Vec3D Bevel Fresnel":            "percent",
	"ADBE Vec3D Bevel Gloss":              "percent",
	"ADBE Vec3D Bevel Metal":              "percent",
	"ADBE Vec3D Bevel Reflection":         "percent",
	"ADBE Vec3D Bevel Shininess":          "percent",
	"ADBE Vec3D Bevel Specular":           "percent",
	"ADBE Vec3D Bevel XparRoll":           "percent",
	"ADBE Vec3D Bevel Xparency":           "percent",
	"ADBE Vec3D Front Ambient":            "percent",
	"ADBE Vec3D Front Diffuse":            "percent",
	"ADBE Vec3D Front Fresnel":            "percent",
	"ADBE Vec3D Front Gloss":              "percent",
	"ADBE Vec3D Front Metal":              "percent",
	"ADBE Vec3D Front Reflection":         "percent",
	"ADBE Vec3D Front Shininess":          "percent",
	"ADBE Vec3D Front Specular":           "percent",
	"ADBE Vec3D Front XparRoll":           "percent",
	"ADBE Vec3D Front Xparency":           "percent",
	"ADBE Vec3D Side Ambient":             "percent",
	"ADBE Vec3D Side Diffuse":             "percent",
	"ADBE Vec3D Side Fresnel":             "percent",
	"ADBE Vec3D Side Gloss":               "percent",
	"ADBE Vec3D Side Metal":               "percent",
	"ADBE Vec3D Side Reflection":          "percent",
	"ADBE Vec3D Side Shininess":           "percent",
	"ADBE Vec3D Side Specular":            "percent",
	"ADBE Vec3D Side XparRoll":            "percent",
	"ADBE Vec3D Side Xparency":            "percent",
	"ADBE Vector Anchor":                  "pixels",
	"ADBE Vector Ellipse Position":        "pixels",
	"ADBE Vector Fill Opacity":            "percent",
	"ADBE Vector Group Opacity":           "percent",
	"ADBE Vector Position":                "pixels",
	"ADBE Vector Rect Position":           "pixels",
	"ADBE Vector Repeater Anchor":         "pixels",
	"ADBE Vector Repeater Opacity 1":      "percent",
	"ADBE Vector Repeater Opacity 2":      "percent",
	"ADBE Vector Repeater Position":       "pixels",
	"ADBE Vector Repeater Rotation":       "degrees",
	"ADBE Vector Repeater Scale":          "percent",
	"ADBE Vector Rotation":                "degrees",
	"ADBE Vector Scale":                   "percent",
	"ADBE Vector Skew Axis":               "degrees",
	"ADBE Vector Star Inner Roundess":     "percent",
	"ADBE Vector Star Outer Roundess":     "percent",
	"ADBE Vector Star Position":           "pixels",
	"ADBE Vector Star Rotation":           "degrees",
	"ADBE Vector Stroke Opacity":          "percent",
	"ADBE Vector Taper End Ease":          "percent",
	"ADBE Vector Taper End Length":        "percent",
	"ADBE Vector Taper End Width":         "percent",
	"ADBE Vector Taper Start Ease":        "percent",
	"ADBE Vector Taper Start Length":      "percent",
	"ADBE Vector Taper Start Width":       "percent",
	"ADBE Vector Taper Wave Amount":       "percent",
	"ADBE Vector Taper Wave Phase":        "degrees",
	"ADBE 3D Tracker-0407":                "percent",
	"ADBE 3D Tracker-0409":                "percent",
	"ADBE 4ColorGradient-0001":            "pixels",
	"ADBE 4ColorGradient-0003":            "pixels",
	"ADBE 4ColorGradient-0005":            "pixels",
	"ADBE 4ColorGradient-0007":            "pixels",
	"ADBE 4ColorGradient-0009":            "percent",
	"ADBE 4ColorGradient-0010":            "percent",
	"ADBE 4ColorGradient-0013":            "percent",
	"ADBE AIF Perlin Noise 3D-0010":       "percent",
	"ADBE AIF Perlin Noise 3D-0011":       "percent",
	"ADBE AIF Perlin Noise 3D-0012":       "percent",
	"ADBE AIF Perlin Noise 3D-0013":       "pixels",
	"ADBE AIF Perlin Noise 3D-0015":       "percent",
	"ADBE AIF Perlin Noise 3D-0025":       "percent",
	"ADBE Aud Delay-0002":                 "percent",
	"ADBE Aud Delay-0003":                 "percent",
	"ADBE Aud Delay-0004":                 "percent",
	"ADBE Aud Delay-0005":                 "percent",
	"ADBE Aud HiLo-0003":                  "percent",
	"ADBE Aud HiLo-0004":                  "percent",
	"ADBE Aud Modulator-0003":             "percent",
	"ADBE Aud Modulator-0004":             "percent",
	"ADBE Aud Reverb-0002":                "percent",
	"ADBE Aud Reverb-0003":                "percent",
	"ADBE Aud Reverb-0004":                "percent",
	"ADBE Aud Reverb-0005":                "percent",
	"ADBE Aud Reverb-0006":                "percent",
	"ADBE Aud Stereo Mixer-0001":          "percent",
	"ADBE Aud Stereo Mixer-0002":          "percent",
	"ADBE Aud Stereo Mixer-0003":          "percent",
	"ADBE Aud Stereo Mixer-0004":          "percent",
	"ADBE Aud Tone-0007":                  "percent",
	"ADBE AudSpect-0002":                  "pixels",
	"ADBE AudSpect-0003":                  "pixels",
	"ADBE AudSpect-0006":                  "percent",
	"ADBE AudSpect-0007":                  "percent",
	"ADBE AudSpect-0009":                  "percent",
	"ADBE AudSpect-0013":                  "percent",
	"ADBE AudWave-0002":                   "pixels",
	"ADBE AudWave-0003":                   "pixels",
	"ADBE AudWave-0006":                   "percent",
	"ADBE AudWave-0010":                   "percent",
	"ADBE Aud_Flange-0004":                "percent",
	"ADBE Aud_Flange-0008":                "percent",
	"ADBE Aud_Flange-0009":                "percent",
	"ADBE AutoColor-0003":                 "percent",
	"ADBE AutoColor-0004":                 "percent",
	"ADBE AutoColor-0006":                 "percent",
	"ADBE AutoContrast-0003":              "percent",
	"ADBE AutoContrast-0004":              "percent",
	"ADBE AutoContrast-0005":              "percent",
	"ADBE AutoLevels-0003":                "percent",
	"ADBE AutoLevels-0004":                "percent",
	"ADBE AutoLevels-0005":                "percent",
	"ADBE BEZMESH-0001":                   "pixels",
	"ADBE BEZMESH-0002":                   "pixels",
	"ADBE BEZMESH-0003":                   "pixels",
	"ADBE BEZMESH-0004":                   "pixels",
	"ADBE BEZMESH-0005":                   "pixels",
	"ADBE BEZMESH-0006":                   "pixels",
	"ADBE BEZMESH-0007":                   "pixels",
	"ADBE BEZMESH-0008":                   "pixels",
	"ADBE BEZMESH-0009":                   "pixels",
	"ADBE BEZMESH-0010":                   "pixels",
	"ADBE BEZMESH-0011":                   "pixels",
	"ADBE BEZMESH-0012":                   "pixels",
	"ADBE Basic Text2-0002":               "pixels",
	"ADBE Blend-0003":                     "percent",
	"ADBE Block Dissolve-0001":            "percent",
	"ADBE Block Dissolve-0002":            "percent",
	"ADBE Block Dissolve-0003":            "percent",
	"ADBE Brightness & Contrast 2-0002":   "pixels",
	"ADBE Brightness & Contrast-0001":     "pixels",
	"ADBE Brightness & Contrast-0002":     "pixels",
	"ADBE Brush Strokes-0007":             "percent",
	"ADBE Bulge-0003":                     "pixels",
	"ADBE Bulge-0004":                     "pixels",
	"ADBE Calculations-0008":              "percent",
	"ADBE Camera Lens Blur-0004":          "percent",
	"ADBE CameraShakeDeblur-0003":         "percent",
	"ADBE CameraShakeDeblur-0004":         "percent",
	"ADBE Cell Pattern-0007":              "pixels",
	"ADBE Change Color-0003":              "pixels",
	"ADBE Change Color-0004":              "pixels",
	"ADBE Change Color-0006":              "percent",
	"ADBE Change Color-0007":              "percent",
	"ADBE Change To Color-0005":           "percent",
	"ADBE Change To Color-0006":           "percent",
	"ADBE Change To Color-0007":           "percent",
	"ADBE Change To Color-0008":           "percent",
	"ADBE Checkerboard-0001":              "pixels",
	"ADBE Checkerboard-0003":              "pixels",
	"ADBE Checkerboard-0004":              "percent",
	"ADBE Checkerboard-0005":              "percent",
	"ADBE Checkerboard-0011":              "percent",
	"ADBE Circle-0001":                    "pixels",
	"ADBE Circle-0011":                    "percent",
	"ADBE Color Balance (HLS)-0002":       "pixels",
	"ADBE Color Balance (HLS)-0003":       "pixels",
	"ADBE Color Balance 2-0001":           "pixels",
	"ADBE Color Balance 2-0002":           "pixels",
	"ADBE Color Balance 2-0003":           "pixels",
	"ADBE Color Balance 2-0004":           "pixels",
	"ADBE Color Balance 2-0005":           "pixels",
	"ADBE Color Balance 2-0006":           "pixels",
	"ADBE Color Balance 2-0007":           "pixels",
	"ADBE Color Balance 2-0008":           "pixels",
	"ADBE Color Balance 2-0009":           "pixels",
	"ADBE Color Balance-0001":             "pixels",
	"ADBE Color Balance-0002":             "pixels",
	"ADBE Color Balance-0003":             "pixels",
	"ADBE Color Emboss-0004":              "percent",
	"ADBE Color Link-0004":                "percent",
	"ADBE Color Swirl-0001":               "percent",
	"ADBE Compound Arithmetic-0006":       "percent",
	"ADBE Corner Pin-0001":                "pixels",
	"ADBE Corner Pin-0002":                "pixels",
	"ADBE Corner Pin-0003":                "pixels",
	"ADBE Corner Pin-0004":                "pixels",
	"ADBE Deflicker-0002":                 "pixels",
	"ADBE Deflicker-0003":                 "pixels",
	"ADBE Deflicker-0004":                 "pixels",
	"ADBE Deflicker-0005":                 "percent",
	"ADBE Difference Matte2-0004":         "percent",
	"ADBE Difference Matte2-0005":         "percent",
	"ADBE ELLIPSE-0001":                   "pixels",
	"ADBE ELLIPSE-0005":                   "percent",
	"ADBE Equalize-0002":                  "percent",
	"ADBE Eyedropper Fill-0001":           "pixels",
	"ADBE Eyedropper Fill-0005":           "percent",
	"ADBE Find Edges-0002":                "percent",
	"ADBE Fractal Noise-0010":             "percent",
	"ADBE Fractal Noise-0011":             "percent",
	"ADBE Fractal Noise-0012":             "percent",
	"ADBE Fractal Noise-0013":             "pixels",
	"ADBE Fractal Noise-0015":             "percent",
	"ADBE Fractal Noise-0020":             "pixels",
	"ADBE Fractal Noise-0029":             "percent",
	"ADBE Gamma/Pedestal/Gain2-0001":      "percent",
	"ADBE Geometry-0001":                  "pixels",
	"ADBE Geometry-0002":                  "pixels",
	"ADBE Getting Jiggy-0003":             "percent",
	"ADBE Getting Jiggy-0007":             "pixels",
	"ADBE Getting Jiggy-0008":             "pixels",
	"ADBE Gradient Wipe-0001":             "percent",
	"ADBE Gradient Wipe-0002":             "percent",
	"ADBE Grid-0001":                      "pixels",
	"ADBE Grid-0003":                      "pixels",
	"ADBE Grid-0004":                      "percent",
	"ADBE Grid-0005":                      "percent",
	"ADBE Grid-0013":                      "percent",
	"ADBE HDR ToneMap-0001":               "percent",
	"ADBE IRIS_WIPE-0001":                 "pixels",
	"ADBE KeyCleaner-0001":                "percent",
	"ADBE KeyCleaner-0016":                "percent",
	"ADBE LIQUIFY-0015":                   "pixels",
	"ADBE LIQUIFY-0016":                   "percent",
	"ADBE Laser-0001":                     "pixels",
	"ADBE Laser-0002":                     "pixels",
	"ADBE Laser-0003":                     "percent",
	"ADBE Laser-0004":                     "percent",
	"ADBE Laser-0007":                     "percent",
	"ADBE Leave Color-0001":               "percent",
	"ADBE Leave Color-0003":               "percent",
	"ADBE Leave Color-0004":               "percent",
	"ADBE Lightning 2-0002":               "pixels",
	"ADBE Lightning 2-0003":               "pixels",
	"ADBE Lightning 2-0007":               "percent",
	"ADBE Lightning 2-0011":               "percent",
	"ADBE Lightning 2-0012":               "percent",
	"ADBE Lightning 2-0015":               "pixels",
	"ADBE Lightning 2-0017":               "percent",
	"ADBE Lightning 2-0024":               "percent",
	"ADBE Lightning 2-0027":               "percent",
	"ADBE Lightning 2-0028":               "percent",
	"ADBE Lightning 2-0029":               "percent",
	"ADBE Lightning-0001":                 "pixels",
	"ADBE Lightning-0002":                 "pixels",
	"ADBE Lightning-0016":                 "percent",
	"ADBE Linear Color Key2-0005":         "percent",
	"ADBE Linear Color Key2-0006":         "percent",
	"ADBE Linear Wipe-0001":               "percent",
	"ADBE Magnify-0001":                   "pixels",
	"ADBE Magnify-0002":                   "percent",
	"ADBE Magnify-0003":                   "pixels",
	"ADBE Magnify-0005":                   "percent",
	"ADBE Matte Choker-0003":              "percent",
	"ADBE Matte Choker-0006":              "percent",
	"ADBE Mirror-0001":                    "pixels",
	"ADBE Noise Alpha-0002":               "percent",
	"ADBE Noise Alpha-0005":               "degrees",
	"ADBE Noise HLS Auto-0002":            "percent",
	"ADBE Noise HLS Auto-0003":            "percent",
	"ADBE Noise HLS Auto-0004":            "percent",
	"ADBE Noise HLS Auto2-0002":           "percent",
	"ADBE Noise HLS Auto2-0003":           "percent",
	"ADBE Noise HLS Auto2-0004":           "percent",
	"ADBE Noise HLS-0002":                 "percent",
	"ADBE Noise HLS-0003":                 "percent",
	"ADBE Noise HLS-0004":                 "percent",
	"ADBE Noise HLS2-0002":                "percent",
	"ADBE Noise HLS2-0003":                "percent",
	"ADBE Noise HLS2-0004":                "percent",
	"ADBE Noise-0001":                     "percent",
	"ADBE Noise2-0001":                    "percent",
	"ADBE Numbers2-0007":                  "pixels",
	"ADBE Offset-0001":                    "pixels",
	"ADBE Offset-0002":                    "percent",
	"ADBE Optics Compensation-0004":       "pixels",
	"ADBE PSL Bevel Emboss-0003":          "percent",
	"ADBE Paint Bucket-0002":              "pixels",
	"ADBE Paint Bucket-0010":              "percent",
	"ADBE Param EQ-0005":                  "percent",
	"ADBE Param EQ-0009":                  "percent",
	"ADBE Param EQ-0013":                  "percent",
	"ADBE Path Text-0017":                 "pixels",
	"ADBE Path Text-0018":                 "pixels",
	"ADBE Path Text-0019":                 "pixels",
	"ADBE Path Text-0020":                 "pixels",
	"ADBE Path Text-0026":                 "pixels",
	"ADBE Path Text-0028":                 "percent",
	"ADBE Photo Filter-0003":              "percent",
	"ADBE PhotoFilterPS-0003":             "percent",
	"ADBE Playgnd-0101":                   "pixels",
	"ADBE Playgnd-0131":                   "pixels",
	"ADBE Point Control-0001":             "pixels",
	"ADBE Point3D Control-0001":           "pixels",
	"ADBE Polar Coordinates-0001":         "percent",
	"ADBE RESHAPE-0004":                   "percent",
	"ADBE Radial Blur-0002":               "pixels",
	"ADBE Radial Shadow-0002":             "percent",
	"ADBE Radial Shadow-0003":             "pixels",
	"ADBE Radial Shadow-0007":             "percent",
	"ADBE Radial Wipe-0001":               "percent",
	"ADBE Radial Wipe-0003":               "pixels",
	"ADBE Ramp-0001":                      "pixels",
	"ADBE Ramp-0003":                      "pixels",
	"ADBE Ramp-0007":                      "percent",
	"ADBE RefineMatte-0006":               "percent",
	"ADBE RefineMatte-0015":               "percent",
	"ADBE RefineMatte-0016":               "percent",
	"ADBE RefineMatte-0022":               "percent",
	"ADBE RefineMatte2-0022":              "percent",
	"ADBE RefineMatte2-0029":              "percent",
	"ADBE RefineMatte2-0030":              "percent",
	"ADBE RefineMatte2-0033":              "percent",
	"ADBE RefineRBMatte-0006":             "percent",
	"ADBE RefineRBMatte-0016":             "percent",
	"ADBE RefineRBMatte-0022":             "percent",
	"ADBE RefineRBMatte-0023":             "percent",
	"ADBE Ripple-0002":                    "pixels",
	"ADBE Ripple-0004":                    "percent",
	"ADBE Rolling Shutter-0001":           "percent",
	"ADBE Rolling Shutter-0006":           "percent",
	"ADBE SCHMEAR-0003":                   "pixels",
	"ADBE SCHMEAR-0006":                   "percent",
	"ADBE Sample Image-0001":              "pixels",
	"ADBE Scribble Fill-0012":             "percent",
	"ADBE Scribble Fill-0024":             "percent",
	"ADBE Scribble Fill-0030":             "percent",
	"ADBE Scribble Fill-0032":             "percent",
	"ADBE Scribble Fill-0046":             "percent",
	"ADBE Scribble Fill-0052":             "percent",
	"ADBE Scribble Fill-0058":             "percent",
	"ADBE Scribble Fill-0066":             "percent",
	"ADBE SelectiveColor-0003":            "percent",
	"ADBE SelectiveColor-0004":            "percent",
	"ADBE SelectiveColor-0005":            "percent",
	"ADBE SelectiveColor-0006":            "percent",
	"ADBE SelectiveColor-0009":            "percent",
	"ADBE SelectiveColor-0010":            "percent",
	"ADBE SelectiveColor-0011":            "percent",
	"ADBE SelectiveColor-0012":            "percent",
	"ADBE SelectiveColor-0015":            "percent",
	"ADBE SelectiveColor-0016":            "percent",
	"ADBE SelectiveColor-0017":            "percent",
	"ADBE SelectiveColor-0018":            "percent",
	"ADBE SelectiveColor-0021":            "percent",
	"ADBE SelectiveColor-0022":            "percent",
	"ADBE SelectiveColor-0023":            "percent",
	"ADBE SelectiveColor-0024":            "percent",
	"ADBE SelectiveColor-0027":            "percent",
	"ADBE SelectiveColor-0028":            "percent",
	"ADBE SelectiveColor-0029":            "percent",
	"ADBE SelectiveColor-0030":            "percent",
	"ADBE SelectiveColor-0033":            "percent",
	"ADBE SelectiveColor-0034":            "percent",
	"ADBE SelectiveColor-0035":            "percent",
	"ADBE SelectiveColor-0036":            "percent",
	"ADBE SelectiveColor-0039":            "percent",
	"ADBE SelectiveColor-0040":            "percent",
	"ADBE SelectiveColor-0041":            "percent",
	"ADBE SelectiveColor-0042":            "percent",
	"ADBE SelectiveColor-0045":            "percent",
	"ADBE SelectiveColor-0046":            "percent",
	"ADBE SelectiveColor-0047":            "percent",
	"ADBE SelectiveColor-0048":            "percent",
	"ADBE SelectiveColor-0051":            "percent",
	"ADBE SelectiveColor-0052":            "percent",
	"ADBE SelectiveColor-0053":            "percent",
	"ADBE SelectiveColor-0054":            "percent",
	"ADBE SelectiveColor-0057":            "percent",
	"ADBE SelectiveColor-0058":            "percent",
	"ADBE SelectiveColor-0059":            "percent",
	"ADBE SelectiveColor-0060":            "percent",
	"ADBE Separate XYZ Scale-0001":        "percent",
	"ADBE Separate XYZ Scale-0002":        "percent",
	"ADBE Separate XYZ Scale-0003":        "percent",
	"ADBE ShadowHighlight-0013":           "percent",
	"ADBE ShadowHighlight-0014":           "percent",
	"ADBE ShadowHighlight-0016":           "percent",
	"ADBE Solid Composite-0001":           "percent",
	"ADBE Solid Composite-0003":           "percent",
	"ADBE Spherize-0002":                  "pixels",
	"ADBE Spill2-1001":                    "percent",
	"ADBE Stereo 3D Controls-0003":        "percent",
	"ADBE Strobe-0002":                    "percent",
	"ADBE Strobe-0005":                    "percent",
	"ADBE Stroke-0004":                    "percent",
	"ADBE Stroke-0005":                    "percent",
	"ADBE Stroke-0006":                    "percent",
	"ADBE Stroke-0008":                    "percent",
	"ADBE Stroke-0009":                    "percent",
	"ADBE SubspaceStabilizer-0003":        "percent",
	"ADBE SubspaceStabilizer-0004":        "percent",
	"ADBE SubspaceStabilizer-0016":        "percent",
	"ADBE SubspaceStabilizer-0020":        "percent",
	"ADBE SubspaceStabilizer-0023":        "percent",
	"ADBE SubspaceStabilizer-0301":        "percent",
	"ADBE Three-Way Color Corrector-0004": "percent",
	"ADBE Tile-0001":                      "pixels",
	"ADBE Timecode-0005":                  "pixels",
	"ADBE Timecode-0012":                  "percent",
	"ADBE Timewarp-0006":                  "percent",
	"ADBE Tritone-0004":                   "percent",
	"ADBE Twirl-0003":                     "pixels",
	"ADBE Unsharp Mask-0001":              "pixels",
	"ADBE Unsharp Mask2-0001":             "pixels",
	"ADBE Upscale-0001":                   "percent",
	"ADBE Upscale-0002":                   "percent",
	"ADBE Upscale-0007":                   "percent",
	"ADBE Venetian Blinds-0001":           "percent",
	"ADBE Venetian Blinds-0003":           "percent",
	"ADBE Wave Warp-0003":                 "percent",
	"ADBE Wave Warp-0005":                 "pixels",
	"ADBE Write-on-0001":                  "pixels",
	"ADBE Write-on-0004":                  "percent",
	"ADBE Write-on-0005":                  "percent",
	"ADBE CM Animated Shape 2-0002":       "pixels",
	"ADBE CM Animated Shape Control-0002": "pixels",
	"ADBE CM CornerReveal-0001":           "percent",
	"ADBE CM CrackedTiles-0001":           "percent",
	"ADBE CM CropEdges-0001":              "percent",
	"ADBE CM DissolveUnmelt-0001":         "percent",
	"ADBE CM FlyToInset-0001":             "percent",
	"ADBE CM FlyToInset-0002":             "percent",
	"ADBE CM FlyToInset-0003":             "pixels",
	"ADBE CM GridWipe-0001":               "percent",
	"ADBE CM InsetVideoFramed-0001":       "percent",
	"ADBE CM InsetVideoTorn-0001":         "percent",
	"ADBE CM LightLeaksRandom-0001":       "percent",
	"ADBE CM MoodLightAmorph-0003":        "percent",
	"ADBE CM MoodLightDigital-0003":       "percent",
	"ADBE CM MoodLightStreaks-0003":       "percent",
	"ADBE CM OpacityFlashRandom-0001":     "percent",
	"ADBE CM ScaleBounceMarkers-0002":     "percent",
	"ADBE CM ScaleBounceRandom-0001":      "percent",
	"ADBE CM ScaleBounceRandom-0003":      "percent",
	"ADBE CM SlideVariable-0001":          "percent",
	"ADBE CM SlideVariable-0003":          "percent",
	"ADBE CM TransCard-0001":              "percent",
	"ADBE CM TransComplete-0001":          "percent",
	"ADBE CM TransCorner-0001":            "percent",
	"ADBE CM TransDissolve-0001":          "percent",
	"ADBE CM TransFade-0001":              "percent",
	"ADBE CM TransFadeMask-0001":          "percent",
	"ADBE CM TransIris-0001":              "percent",
	"ADBE CM TransRadial-0001":            "percent",
	"ADBE CM TransSlide-0001":             "percent",
	"ADBE CM TransStretch-0001":           "percent",
	"ADBE CM TransWipe-0001":              "percent",
	"ADBE CM TransWipeFeath-0001":         "percent",
	"ADBE CM WiggleScale-0002":            "percent",
	"ADBE CM WiggleScale-0004":            "percent",
	"ADBE CM Wigglerama-0005":             "percent",
	"ADBE CM Wigglerama-0007":             "percent",
	"ADBE CM Zoom2DSpin-0001":             "percent",
	"ADBE CM Zoom3DTumble-0001":           "percent",
	"ADBE CM ZoomBubble-0001":             "percent",
	"ADBE CM ZoomSpiral-0001":             "percent",
	"ADBE CM ZoomWobble-0001":             "percent",
	"bevelEmboss/highlightOpacity":        "percent",
	"bevelEmboss/localLightingAltitude":   "degrees",
	"bevelEmboss/localLightingAngle":      "degrees",
	"bevelEmboss/shadowOpacity":           "percent",
	"bevelEmboss/strengthRatio":           "percent",
	"chromeFX/localLightingAngle":         "degrees",
	"chromeFX/opacity":                    "percent",
	"dropShadow/chokeMatte":               "percent",
	"dropShadow/localLightingAngle":       "degrees",
	"dropShadow/noise":                    "percent",
	"dropShadow/opacity":                  "percent",
	"frameFX/opacity":                     "percent",
	"gradientFill/angle":                  "degrees",
	"gradientFill/gradientSmoothness":     "percent",
	"gradientFill/offset":                 "pixels",
	"gradientFill/opacity":                "percent",
	"gradientFill/scale":                  "percent",
	"innerGlow/chokeMatte":                "percent",
	"innerGlow/gradientSmoothness":        "percent",
	"innerGlow/inputRange":                "percent",
	"innerGlow/noise":                     "percent",
	"innerGlow/opacity":                   "percent",
	"innerGlow/shadingNoise":              "percent",
	"innerShadow/chokeMatte":              "percent",
	"innerShadow/localLightingAngle":      "degrees",
	"innerShadow/noise":                   "percent",
	"innerShadow/opacity":                 "percent",
	"outerGlow/chokeMatte":                "percent",
	"outerGlow/gradientSmoothness":        "percent",
	"outerGlow/inputRange":                "percent",
	"outerGlow/noise":                     "percent",
	"outerGlow/opacity":                   "percent",
	"outerGlow/shadingNoise":              "percent",
	"patternFill/opacity":                 "percent",
	"patternFill/phase":                   "pixels",
	"patternFill/scale":                   "percent",
	"solidFill/opacity":                   "percent",
}
