package recipedoc

var capabilitiesByPath = map[string][]string{
	"project.target_version":                                      {"project.create_target"},
	"comps[]":                                                     {"comp.create"},
	"comps[].background_color":                                    {"comp.set_background_color"},
	"comps[].label":                                               {"comp.set_label"},
	"comps[].comment":                                             {"comp.set_comment"},
	"comps[].renderer":                                            {"comp.set_renderer"},
	"comps[].resolution_factor":                                   {"comp.set_resolution_factor"},
	"comps[].pixel_aspect":                                        {"comp.set_pixel_aspect"},
	"comps[].display_start_time":                                  {"comp.set_display_start_time"},
	"comps[].frame_blending":                                      {"comp.set_frame_blending"},
	"comps[].draft_3d":                                            {"comp.set_draft_3d"},
	"comps[].hide_shy_layers":                                     {"comp.set_hide_shy_layers"},
	"comps[].preserve_nested_frame_rate":                          {"comp.set_preserve_nested_frame_rate"},
	"comps[].preserve_nested_resolution":                          {"comp.set_preserve_nested_resolution"},
	"comps[].motion_blur.enabled":                                 {"comp.set_motion_blur"},
	"comps[].motion_blur.shutter_angle":                           {"comp.set_motion_blur_shutter_angle"},
	"comps[].motion_blur.shutter_phase":                           {"comp.set_motion_blur_shutter_phase"},
	"comps[].motion_blur.adaptive_sample_limit":                   {"comp.set_motion_blur_adaptive_sample_limit"},
	"comps[].motion_blur.samples_per_frame":                       {"comp.set_motion_blur_samples_per_frame"},
	"comps[].work_area":                                           {"comp.set_work_area"},
	"comps[].work_area.start":                                     {"comp.set_work_area"},
	"comps[].work_area.end":                                       {"comp.set_work_area"},
	"comps[].layers[].type":                                       {"layer.create_text", "layer.create_shape", "layer.create_solid", "layer.create_camera", "layer.create_light", "layer.create_null", "layer.create_adjustment"},
	"comps[].layers[].label":                                      {"layer.set_label"},
	"comps[].layers[].comment":                                    {"layer.set_comment"},
	"comps[].layers[].visible":                                    {"layer.set_visible"},
	"comps[].layers[].solo":                                       {"layer.set_solo"},
	"comps[].layers[].locked":                                     {"layer.set_locked"},
	"comps[].layers[].motion_blur":                                {"layer.set_motion_blur"},
	"comps[].layers[].shy":                                        {"layer.set_shy"},
	"comps[].layers[].effects_enabled":                            {"layer.set_effects_enabled"},
	"comps[].layers[].audio_enabled":                              {"layer.set_audio_enabled"},
	"comps[].layers[].frame_blend_enabled":                        {"layer.set_frame_blend_enabled"},
	"comps[].layers[].markers_locked":                             {"layer.set_markers_locked"},
	"comps[].layers[].collapse_transform":                         {"layer.set_collapse_transform"},
	"comps[].layers[].is_3d":                                      {"layer.set_is_3d"},
	"comps[].layers[].is_adjust":                                  {"layer.set_is_adjust"},
	"comps[].layers[].is_null":                                    {"layer.set_is_null"},
	"comps[].layers[].is_guide":                                   {"layer.set_is_guide"},
	"comps[].layers[].sampling_bicubic":                           {"layer.set_sampling_bicubic"},
	"comps[].layers[].frame_blend_pixel_motion":                   {"layer.set_frame_blend_pixel_motion"},
	"comps[].layers[].preserve_transparency":                      {"layer.set_preserve_transparency"},
	"comps[].layers[].quality":                                    {"layer.set_quality"},
	"comps[].layers[].blending_mode":                              {"layer.set_blending_mode"},
	"comps[].layers[].track_matte":                                {"layer.set_track_matte"},
	"comps[].layers[].matte":                                      {"layer.set_track_matte_source"},
	"comps[].layers[].auto_orient":                                {"layer.set_auto_orient"},
	"comps[].layers[].start_time":                                 {"layer.set_start_time"},
	"comps[].layers[].in_point":                                   {"layer.set_in_point"},
	"comps[].layers[].out_point":                                  {"layer.set_out_point"},
	"comps[].layers[].parent":                                     {"layer.set_parent"},
	"comps[].layers[].text":                                       {"layer.set_text"},
	"comps[].layers[].text_animators[]":                           {"text_animator.add_opacity", "text_animator.add_position", "text_animator.add_scale", "text_animator.add_rotation", "text_animator.add_color", "text_animator.add_tracking", "text_animator.add_character_offset", "text_animator.add_fill_opacity", "text_animator.add_stroke_opacity"},
	"comps[].layers[].text_animators[].range_offset_keyframes[]":  {"text_animator.animate_range_offset"},
	"comps[].layers[].text_style.font_size":                       {"text.set_run_font_size"},
	"comps[].layers[].text_style.fill_color":                      {"text.set_run_fill_color"},
	"comps[].layers[].text_style.tracking":                        {"text.set_run_tracking"},
	"comps[].layers[].text_style.faux_bold":                       {"text.set_run_faux_bold"},
	"comps[].layers[].text_style.faux_italic":                     {"text.set_run_faux_italic"},
	"comps[].layers[].text_style.apply_stroke":                    {"text.set_run_apply_stroke"},
	"comps[].layers[].text_style.stroke_color":                    {"text.set_run_stroke_color"},
	"comps[].layers[].text_style.stroke_width":                    {"text.set_run_stroke_width"},
	"comps[].layers[].text_style.justification":                   {"text.set_paragraph_justification"},
	"comps[].layers[].camera.zoom":                                {"camera.set_zoom"},
	"comps[].layers[].camera.depth_of_field":                      {"camera.set_depth_of_field"},
	"comps[].layers[].camera.focus_distance":                      {"camera.set_focus_distance"},
	"comps[].layers[].camera.aperture":                            {"camera.set_aperture"},
	"comps[].layers[].camera.blur_level":                          {"camera.set_blur_level"},
	"comps[].layers[].camera.iris_shape":                          {"camera.set_iris_shape"},
	"comps[].layers[].camera.iris_rotation":                       {"camera.set_iris_rotation"},
	"comps[].layers[].camera.iris_roundness":                      {"camera.set_iris_roundness"},
	"comps[].layers[].camera.iris_aspect_ratio":                   {"camera.set_iris_aspect_ratio"},
	"comps[].layers[].camera.iris_diffraction_fringe":             {"camera.set_iris_diffraction_fringe"},
	"comps[].layers[].camera.iris_highlight_gain":                 {"camera.set_iris_highlight_gain"},
	"comps[].layers[].camera.iris_highlight_threshold":            {"camera.set_iris_highlight_threshold"},
	"comps[].layers[].camera.iris_highlight_saturation":           {"camera.set_iris_highlight_saturation"},
	"comps[].layers[].light.kind":                                 {"light.set_kind"},
	"comps[].layers[].light.source_layer":                         {"light.set_source_layer"},
	"comps[].layers[].light.intensity":                            {"light.set_intensity"},
	"comps[].layers[].light.color":                                {"light.set_color"},
	"comps[].layers[].light.casts_shadows":                        {"light.set_casts_shadows"},
	"comps[].layers[].light.shadow_darkness":                      {"light.set_shadow_darkness"},
	"comps[].layers[].light.shadow_diffusion":                     {"light.set_shadow_diffusion"},
	"comps[].layers[].light.falloff_type":                         {"light.set_falloff_type"},
	"comps[].layers[].light.falloff_start":                        {"light.set_falloff_start"},
	"comps[].layers[].light.falloff_distance":                     {"light.set_falloff_distance"},
	"comps[].layers[].light.cone_angle":                           {"light.set_cone_angle"},
	"comps[].layers[].light.cone_feather":                         {"light.set_cone_feather"},
	"comps[].layers[].shape.kind":                                 {"shape.star.add", "shape.star.set_type"},
	"comps[].layers[].shape.size":                                 {"shape.rect.set_size", "shape.ellipse.set_size"},
	"comps[].layers[].shape.position":                             {"shape.rect.set_position", "shape.ellipse.set_position", "shape.star.set_position"},
	"comps[].layers[].shape.roundness":                            {"shape.rect.set_roundness"},
	"comps[].layers[].shape.points":                               {"shape.star.set_points"},
	"comps[].layers[].shape.rotation":                             {"shape.star.set_rotation"},
	"comps[].layers[].shape.inner_radius":                         {"shape.star.set_inner_radius"},
	"comps[].layers[].shape.outer_radius":                         {"shape.star.set_outer_radius"},
	"comps[].layers[].shape.inner_roundness":                      {"shape.star.set_inner_roundness"},
	"comps[].layers[].shape.outer_roundness":                      {"shape.star.set_outer_roundness"},
	"comps[].layers[].shape.fill_color":                           {"shape.fill.set_color"},
	"comps[].layers[].shape.fill_opacity":                         {"shape.fill.set_opacity"},
	"comps[].layers[].shape.fill_blend_mode":                      {"shape.fill.set_blend_mode"},
	"comps[].layers[].shape.fill_composite_order":                 {"shape.fill.set_composite_order"},
	"comps[].layers[].shape.fill_rule":                            {"shape.fill.set_fill_rule"},
	"comps[].layers[].shape.gradient_fill":                        {"shape.gradient_fill.add"},
	"comps[].layers[].shape.gradient_fill.type":                   {"shape.gradient_fill.set_type"},
	"comps[].layers[].shape.gradient_fill.start_point":            {"shape.gradient_fill.set_start_point"},
	"comps[].layers[].shape.gradient_fill.end_point":              {"shape.gradient_fill.set_end_point"},
	"comps[].layers[].shape.gradient_fill.highlight_length":       {"shape.gradient_fill.set_highlight_length"},
	"comps[].layers[].shape.gradient_fill.highlight_angle":        {"shape.gradient_fill.set_highlight_angle"},
	"comps[].layers[].shape.gradient_fill.color_stops[]":          {"shape.gradient_fill.set_color_stops"},
	"comps[].layers[].shape.gradient_fill.alpha_stops[]":          {"shape.gradient_fill.set_alpha_stops"},
	"comps[].layers[].shape.gradient_stroke":                      {"shape.gradient_stroke.add"},
	"comps[].layers[].shape.gradient_stroke.type":                 {"shape.gradient_stroke.set_type"},
	"comps[].layers[].shape.gradient_stroke.start_point":          {"shape.gradient_stroke.set_start_point"},
	"comps[].layers[].shape.gradient_stroke.end_point":            {"shape.gradient_stroke.set_end_point"},
	"comps[].layers[].shape.gradient_stroke.highlight_length":     {"shape.gradient_stroke.set_highlight_length"},
	"comps[].layers[].shape.gradient_stroke.highlight_angle":      {"shape.gradient_stroke.set_highlight_angle"},
	"comps[].layers[].shape.gradient_stroke.width":                {"shape.gradient_stroke.set_width"},
	"comps[].layers[].shape.gradient_stroke.line_cap":             {"shape.gradient_stroke.set_line_cap"},
	"comps[].layers[].shape.gradient_stroke.line_join":            {"shape.gradient_stroke.set_line_join"},
	"comps[].layers[].shape.gradient_stroke.miter_limit":          {"shape.gradient_stroke.set_miter_limit"},
	"comps[].layers[].shape.gradient_stroke.color_stops[]":        {"shape.gradient_stroke.set_color_stops"},
	"comps[].layers[].shape.gradient_stroke.alpha_stops[]":        {"shape.gradient_stroke.set_alpha_stops"},
	"comps[].layers[].shape.stroke":                               {"shape.stroke.add"},
	"comps[].layers[].shape.stroke.color":                         {"shape.stroke.set_color"},
	"comps[].layers[].shape.stroke.width":                         {"shape.stroke.set_width"},
	"comps[].layers[].shape.stroke.opacity":                       {"shape.stroke.set_opacity"},
	"comps[].layers[].shape.stroke.line_cap":                      {"shape.stroke.set_line_cap"},
	"comps[].layers[].shape.stroke.line_join":                     {"shape.stroke.set_line_join"},
	"comps[].layers[].shape.stroke.miter_limit":                   {"shape.stroke.set_miter_limit"},
	"comps[].layers[].shape.stroke.composite_order":               {"shape.stroke.set_composite_order"},
	"comps[].layers[].shape.stroke.taper.start_length":            {"shape.stroke_taper.set_start_length"},
	"comps[].layers[].shape.stroke.taper.end_length":              {"shape.stroke_taper.set_end_length"},
	"comps[].layers[].shape.stroke.taper.start_width":             {"shape.stroke_taper.set_start_width"},
	"comps[].layers[].shape.stroke.taper.end_width":               {"shape.stroke_taper.set_end_width"},
	"comps[].layers[].shape.stroke.taper.start_ease":              {"shape.stroke_taper.set_start_ease"},
	"comps[].layers[].shape.stroke.taper.end_ease":                {"shape.stroke_taper.set_end_ease"},
	"comps[].layers[].shape.stroke.wave.amount":                   {"shape.stroke_wave.set_amount"},
	"comps[].layers[].shape.stroke.wave.wavelength":               {"shape.stroke_wave.set_wavelength"},
	"comps[].layers[].shape.stroke.wave.phase":                    {"shape.stroke_wave.set_phase"},
	"comps[].layers[].shape.stroke.dashes.dash":                   {"shape.stroke_dashes.set_dash"},
	"comps[].layers[].shape.stroke.dashes.gap":                    {"shape.stroke_dashes.set_gap"},
	"comps[].layers[].shape.trim":                                 {"shape.trim.add"},
	"comps[].layers[].shape.round_corners":                        {"shape.round_corners.add"},
	"comps[].layers[].shape.round_corners.radius":                 {"shape.round_corners.set_radius"},
	"comps[].layers[].shape.offset_paths":                         {"shape.offset_paths.add"},
	"comps[].layers[].shape.offset_paths.amount":                  {"shape.offset_paths.set_amount"},
	"comps[].layers[].shape.offset_paths.line_join":               {"shape.offset_paths.set_line_join"},
	"comps[].layers[].shape.offset_paths.miter_limit":             {"shape.offset_paths.set_miter_limit"},
	"comps[].layers[].shape.offset_paths.copies":                  {"shape.offset_paths.set_copies"},
	"comps[].layers[].shape.offset_paths.copy_offset":             {"shape.offset_paths.set_copy_offset"},
	"comps[].layers[].shape.repeater":                             {"shape.repeater.add"},
	"comps[].layers[].shape.repeater.copies":                      {"shape.repeater.set_copies"},
	"comps[].layers[].shape.repeater.offset":                      {"shape.repeater.set_offset"},
	"comps[].layers[].shape.repeater.order":                       {"shape.repeater.set_order"},
	"comps[].layers[].shape.repeater.anchor":                      {"shape.repeater_transform.set_anchor"},
	"comps[].layers[].shape.repeater.position":                    {"shape.repeater_transform.set_position"},
	"comps[].layers[].shape.repeater.scale":                       {"shape.repeater_transform.set_scale"},
	"comps[].layers[].shape.repeater.rotation":                    {"shape.repeater_transform.set_rotation"},
	"comps[].layers[].shape.repeater.start_opacity":               {"shape.repeater_transform.set_start_opacity"},
	"comps[].layers[].shape.repeater.end_opacity":                 {"shape.repeater_transform.set_end_opacity"},
	"comps[].layers[].shape.merge_paths":                          {"shape.merge_paths.add"},
	"comps[].layers[].shape.merge_paths.type":                     {"shape.merge_paths.set_type"},
	"comps[].layers[].shape.zigzag":                               {"shape.zigzag.add"},
	"comps[].layers[].shape.zigzag.size":                          {"shape.zigzag.set_size"},
	"comps[].layers[].shape.zigzag.detail":                        {"shape.zigzag.set_detail"},
	"comps[].layers[].shape.zigzag.points":                        {"shape.zigzag.set_points"},
	"comps[].layers[].shape.pucker_bloat":                         {"shape.pucker_bloat.add"},
	"comps[].layers[].shape.pucker_bloat.amount":                  {"shape.pucker_bloat.set_amount"},
	"comps[].layers[].shape.twist":                                {"shape.twist.add"},
	"comps[].layers[].shape.twist.angle":                          {"shape.twist.set_angle"},
	"comps[].layers[].shape.twist.center":                         {"shape.twist.set_center"},
	"comps[].layers[].shape.wiggle_paths":                         {"shape.wiggle_paths.add"},
	"comps[].layers[].shape.wiggle_paths.size":                    {"shape.wiggle_paths.set_size"},
	"comps[].layers[].shape.wiggle_paths.detail":                  {"shape.wiggle_paths.set_detail"},
	"comps[].layers[].shape.wiggle_paths.wiggles_per_second":      {"shape.wiggle_paths.set_wiggles_per_second"},
	"comps[].layers[].shape.wiggle_paths.random_seed":             {"shape.wiggle_paths.set_random_seed"},
	"comps[].layers[].shape.wiggle_paths.points":                  {"shape.wiggle_paths.set_points"},
	"comps[].layers[].shape.wiggle_paths.correlation":             {"shape.wiggle_paths.set_correlation"},
	"comps[].layers[].shape.wiggle_paths.temporal_phase":          {"shape.wiggle_paths.set_temporal_phase"},
	"comps[].layers[].shape.wiggle_paths.spatial_phase":           {"shape.wiggle_paths.set_spatial_phase"},
	"comps[].layers[].shape.wiggle_transform":                     {"shape.wiggle_transform.add"},
	"comps[].layers[].shape.wiggle_transform.anchor":              {"shape.wiggler_transform.set_anchor"},
	"comps[].layers[].shape.wiggle_transform.position":            {"shape.wiggler_transform.set_position"},
	"comps[].layers[].shape.wiggle_transform.scale":               {"shape.wiggler_transform.set_scale"},
	"comps[].layers[].shape.wiggle_transform.rotation":            {"shape.wiggler_transform.set_rotation"},
	"comps[].layers[].shape.wiggle_transform.wiggles_per_second":  {"shape.wiggle_transform.set_wiggles_per_second"},
	"comps[].layers[].shape.wiggle_transform.random_seed":         {"shape.wiggle_transform.set_random_seed"},
	"comps[].layers[].shape.wiggle_transform.correlation":         {"shape.wiggle_transform.set_correlation"},
	"comps[].layers[].shape.wiggle_transform.temporal_phase":      {"shape.wiggle_transform.set_temporal_phase"},
	"comps[].layers[].shape.wiggle_transform.spatial_phase":       {"shape.wiggle_transform.set_spatial_phase"},
	"comps[].layers[].masks[]":                                    {"mask.add"},
	"comps[].layers[].masks[].name":                               {"mask.add"},
	"comps[].layers[].masks[].mode":                               {"mask.set_mode"},
	"comps[].layers[].masks[].inverted":                           {"mask.set_inverted"},
	"comps[].layers[].masks[].locked":                             {"mask.set_locked"},
	"comps[].layers[].masks[].color":                              {"mask.set_color"},
	"comps[].layers[].masks[].motion_blur":                        {"mask.set_motion_blur"},
	"comps[].layers[].masks[].feather_falloff":                    {"mask.set_feather_falloff"},
	"comps[].layers[].masks[].opacity":                            {"mask.set_opacity"},
	"comps[].layers[].masks[].feather":                            {"mask.set_feather"},
	"comps[].layers[].masks[].expansion":                          {"mask.set_expansion"},
	"comps[].layers[].masks[].closed":                             {"mask.add"},
	"comps[].layers[].masks[].vertices":                           {"mask.add"},
	"comps[].layers[].masks[].path_keyframes[]":                   {"mask.set_path_keyframes"},
	"comps[].layers[].masks[].path_keyframes[].time":              {"mask.set_path_keyframes"},
	"comps[].layers[].masks[].path_keyframes[].vertices":          {"mask.set_path_keyframes"},
	"comps[].layers[].transform":                                  {"layer.set_transform"},
	"comps[].layers[].effects[]":                                  {"effect.add_builtin"},
	"comps[].layers[].effects[].params[]":                         {"effect.set_param"},
	"comps[].layers[].effects[].params[].expression.source":       {"property.set_expression"},
	"comps[].layers[].transform.expressions.position.source":      {"property.set_expression"},
	"comps[].layers[].transform.expressions.anchor_point.source":  {"property.set_expression"},
	"comps[].layers[].transform.expressions.scale.source":         {"property.set_expression"},
	"comps[].layers[].transform.expressions.rotation.source":      {"property.set_expression"},
	"comps[].layers[].transform.expressions.opacity.source":       {"property.set_expression"},
	"comps[].layers[].transform.expressions.position.enabled":     {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.anchor_point.enabled": {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.scale.enabled":        {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.rotation.enabled":     {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.opacity.enabled":      {"property.set_expression_enabled"},
	"comps[].layers[].effects[].params[].expression.enabled":      {"property.set_expression_enabled"},
}

var capabilityRegistry = map[string]CapabilityMeta{
	"project.create_target":       {Query: "NewProject", Summary: "Create a project from a target AE template."},
	"comp.create":                 {Query: "NewComposition", Summary: "Create a composition."},
	"comp.set_background_color":   {Query: "Composition.SetBGColor", Summary: "Set composition background color."},
	"comp.set_label":              {Query: "Composition.SetLabel", Summary: "Set composition label color."},
	"comp.set_comment":            {Query: "Composition.SetComment", Summary: "Set composition comment."},
	"comp.set_renderer":           {Query: "SetRenderer", Summary: "Set composition renderer."},
	"comp.set_resolution_factor":  {Query: "Composition.SetResolutionFactor", Summary: "Set composition preview resolution factor."},
	"comp.set_pixel_aspect":       {Query: "Composition.SetPixelAspect", Summary: "Set composition pixel aspect ratio."},
	"comp.set_display_start_time": {Query: "Composition.SetDisplayStartTime", Summary: "Set composition display start time."},
	"comp.set_frame_blending":     {Query: "Composition.SetFrameBlending", Summary: "Set composition frame blending."},
	"comp.set_draft_3d":           {Query: "Composition.SetDraft3D", Summary: "Set composition draft 3D switch."},
	"comp.set_hide_shy_layers":    {Query: "Composition.SetHideShyLayers", Summary: "Set composition shy-layer visibility."},
	"comp.set_preserve_nested_frame_rate": {
		Query:   "Composition.SetPreserveNestedFrameRate",
		Summary: "Set nested frame-rate preservation.",
	},
	"comp.set_preserve_nested_resolution": {
		Query:   "Composition.SetPreserveNestedResolution",
		Summary: "Set nested resolution preservation.",
	},
	"comp.set_motion_blur":                       {Query: "Composition.SetCompMotionBlur", Summary: "Set composition motion blur."},
	"comp.set_motion_blur_shutter_angle":         {Query: "Composition.SetShutterAngle", Summary: "Set composition shutter angle."},
	"comp.set_motion_blur_shutter_phase":         {Query: "Composition.SetShutterPhase", Summary: "Set composition shutter phase."},
	"comp.set_motion_blur_adaptive_sample_limit": {Query: "Composition.SetMotionBlurAdaptiveSampleLimit", Summary: "Set motion blur adaptive sample limit."},
	"comp.set_motion_blur_samples_per_frame":     {Query: "Composition.SetMotionBlurSamplesPerFrame", Summary: "Set motion blur samples per frame."},
	"comp.set_work_area":                         {Query: "Composition.SetWorkArea", Summary: "Set composition work area."},
	"layer.create_text":                          {Query: "NewTextLayer", Summary: "Create a text layer."},
	"layer.create_shape":                         {Query: "NewShapeLayer", Summary: "Create a shape layer."},
	"layer.create_solid":                         {Query: "NewSolidLayer", Summary: "Create a solid layer."},
	"layer.create_camera":                        {Query: "NewCameraLayer", Summary: "Create a camera layer."},
	"layer.create_light":                         {Query: "NewLightLayer", Summary: "Create a light layer."},
	"layer.create_null":                          {Query: "NewNullLayer", Summary: "Create a null layer."},
	"layer.create_adjustment":                    {Query: "NewAdjustmentLayer", Summary: "Create an adjustment layer."},
	"layer.set_label":                            {Query: "Layer.SetLabel", Summary: "Set layer label color."},
	"layer.set_comment":                          {Query: "Layer.SetComment", Summary: "Set layer comment."},
	"layer.set_visible":                          {Query: "Layer.SetVisible", Summary: "Set layer visibility."},
	"layer.set_solo":                             {Query: "Layer.SetSolo", Summary: "Set layer solo switch."},
	"layer.set_locked":                           {Query: "Layer.SetLocked", Summary: "Set layer lock switch."},
	"layer.set_motion_blur":                      {Query: "Layer.SetMotionBlur", Summary: "Set layer motion blur."},
	"layer.set_shy":                              {Query: "Layer.SetShy", Summary: "Set layer shy switch."},
	"layer.set_effects_enabled":                  {Query: "Layer.SetEffectsEnabled", Summary: "Set layer effects switch."},
	"layer.set_audio_enabled":                    {Query: "Layer.SetAudioEnabled", Summary: "Set layer audio switch."},
	"layer.set_frame_blend_enabled":              {Query: "Layer.SetFrameBlendEnabled", Summary: "Set layer frame blending."},
	"layer.set_markers_locked":                   {Query: "Layer.SetMarkersLocked", Summary: "Set layer marker lock switch."},
	"layer.set_collapse_transform":               {Query: "Layer.SetCollapseTransform", Summary: "Set collapse transformations."},
	"layer.set_is_3d":                            {Query: "Layer.SetIs3D", Summary: "Set layer 3D switch."},
	"layer.set_is_adjust":                        {Query: "Layer.SetIsAdjust", Summary: "Set adjustment-layer switch."},
	"layer.set_is_null":                          {Query: "Layer.SetIsNull", Summary: "Set null-layer switch."},
	"layer.set_is_guide":                         {Query: "Layer.SetIsGuide", Summary: "Set guide-layer switch."},
	"layer.set_sampling_bicubic":                 {Query: "Layer.SetSamplingBicubic", Summary: "Set bicubic sampling switch."},
	"layer.set_frame_blend_pixel_motion": {
		Query:   "Layer.SetFrameBlendPixelMotion",
		Summary: "Set pixel-motion frame blending.",
	},
	"layer.set_preserve_transparency":    {Query: "Layer.SetPreserveTransparency", Summary: "Set preserve transparency switch."},
	"layer.set_quality":                  {Query: "Layer.SetQuality", Summary: "Set layer quality mode."},
	"layer.set_blending_mode":            {Query: "Layer.SetBlendingMode", Summary: "Set layer blending mode."},
	"layer.set_track_matte":              {Query: "Layer.SetTrackMatte", Summary: "Set layer track matte."},
	"layer.set_track_matte_source":       {Query: "Layer.SetTrackMatteSource", Summary: "Set explicit track matte source."},
	"layer.set_auto_orient":              {Query: "Layer.SetAutoOrient", Summary: "Set layer auto orientation."},
	"layer.set_start_time":               {Query: "Layer.SetStartTime", Summary: "Set layer start time."},
	"layer.set_in_point":                 {Query: "Layer.SetInPoint", Summary: "Set layer in point."},
	"layer.set_out_point":                {Query: "Layer.SetOutPoint", Summary: "Set layer out point."},
	"layer.set_parent":                   {Query: "Layer.SetParent", Summary: "Set layer parent."},
	"layer.set_text":                     {Query: "Layer.SetText", Summary: "Set text layer source text."},
	"text_animator.add_opacity":          {Query: "AddTextOpacityAnimator", Summary: "Add an opacity text animator."},
	"text_animator.add_position":         {Query: "AddTextPositionAnimator", Summary: "Add a position text animator."},
	"text_animator.add_scale":            {Query: "AddTextScaleAnimator", Summary: "Add a scale text animator."},
	"text_animator.add_rotation":         {Query: "AddTextRotationAnimator", Summary: "Add a rotation text animator."},
	"text_animator.add_color":            {Query: "AddTextColorAnimator", Summary: "Add a fill-color text animator."},
	"text_animator.add_tracking":         {Query: "AddTextTrackingAnimator", Summary: "Add a tracking text animator."},
	"text_animator.add_character_offset": {Query: "AddTextCharacterOffsetAnimator", Summary: "Add a character-offset text animator."},
	"text_animator.add_fill_opacity":     {Query: "AddTextFillOpacityAnimator", Summary: "Add a fill-opacity text animator."},
	"text_animator.add_stroke_opacity":   {Query: "AddTextStrokeOpacityAnimator", Summary: "Add a stroke-opacity text animator."},
	"text_animator.animate_range_offset": {Query: "AnimateTextRangeOffset", Summary: "Keyframe a text animator range selector offset."},
	"layer.set_transform":                {Query: "SetLayerTransform", Summary: "Set layer transform values."},
	"text.set_run_font_size":             {Query: "Layer.SetRunFontSize", Summary: "Set text run font size."},
	"text.set_run_fill_color":            {Query: "Layer.SetRunFillColor", Summary: "Set text run fill color."},
	"text.set_run_tracking":              {Query: "Layer.SetRunTracking", Summary: "Set text run tracking."},
	"text.set_run_faux_bold":             {Query: "Layer.SetRunFauxBold", Summary: "Set text run faux bold."},
	"text.set_run_faux_italic":           {Query: "Layer.SetRunFauxItalic", Summary: "Set text run faux italic."},
	"text.set_run_apply_stroke":          {Query: "Layer.SetRunApplyStroke", Summary: "Set text run stroke enable switch."},
	"text.set_run_stroke_color":          {Query: "Layer.SetRunStrokeColor", Summary: "Set text run stroke color."},
	"text.set_run_stroke_width":          {Query: "Layer.SetRunStrokeWidth", Summary: "Set text run stroke width."},
	"text.set_paragraph_justification": {
		Query:   "Layer.SetParagraphJustification",
		Summary: "Set paragraph justification.",
	},
	"camera.set_zoom":                      {Query: "Layer.SetCameraZoom", Summary: "Set camera zoom."},
	"camera.set_depth_of_field":            {Query: "Layer.SetCameraDepthOfField", Summary: "Set camera depth of field."},
	"camera.set_focus_distance":            {Query: "Layer.SetCameraFocusDistance", Summary: "Set camera focus distance."},
	"camera.set_aperture":                  {Query: "Layer.SetCameraAperture", Summary: "Set camera aperture."},
	"camera.set_blur_level":                {Query: "Layer.SetCameraBlurLevel", Summary: "Set camera blur level."},
	"camera.set_iris_shape":                {Query: "Layer.SetIrisShape", Summary: "Set camera iris shape."},
	"camera.set_iris_rotation":             {Query: "Layer.SetIrisRotation", Summary: "Set camera iris rotation."},
	"camera.set_iris_roundness":            {Query: "Layer.SetIrisRoundness", Summary: "Set camera iris roundness."},
	"camera.set_iris_aspect_ratio":         {Query: "Layer.SetIrisAspectRatio", Summary: "Set camera iris aspect ratio."},
	"camera.set_iris_diffraction_fringe":   {Query: "Layer.SetIrisDiffractionFringe", Summary: "Set camera iris diffraction fringe."},
	"camera.set_iris_highlight_gain":       {Query: "Layer.SetIrisHighlightGain", Summary: "Set camera iris highlight gain."},
	"camera.set_iris_highlight_threshold":  {Query: "Layer.SetIrisHighlightThreshold", Summary: "Set camera iris highlight threshold."},
	"camera.set_iris_highlight_saturation": {Query: "Layer.SetIrisHighlightSaturation", Summary: "Set camera iris highlight saturation."},
	"light.set_kind":                       {Query: "Layer.SetLightKind", Summary: "Set light kind."},
	"light.set_source_layer":               {Query: "Layer.SetLightSource", Summary: "Set light source layer."},
	"light.set_intensity":                  {Query: "Layer.SetLightIntensity", Summary: "Set light intensity."},
	"light.set_color":                      {Query: "Layer.SetLightColor", Summary: "Set light color."},
	"light.set_casts_shadows":              {Query: "Layer.SetLightCastsShadows", Summary: "Set light shadow-casting switch."},
	"light.set_shadow_darkness":            {Query: "Layer.SetLightShadowDarkness", Summary: "Set light shadow darkness."},
	"light.set_shadow_diffusion":           {Query: "Layer.SetLightShadowDiffusion", Summary: "Set light shadow diffusion."},
	"light.set_falloff_type":               {Query: "Layer.SetLightFalloffType", Summary: "Set light falloff type."},
	"light.set_falloff_start":              {Query: "Layer.SetLightFalloffStart", Summary: "Set light falloff start."},
	"light.set_falloff_distance":           {Query: "Layer.SetLightFalloffDistance", Summary: "Set light falloff distance."},
	"light.set_cone_angle":                 {Query: "Layer.SetLightConeAngle", Summary: "Set spotlight cone angle."},
	"light.set_cone_feather":               {Query: "Layer.SetLightConeFeather", Summary: "Set spotlight cone feather."},
	"shape.rect.set_size":                  {Query: "RectNode.SetSize", Summary: "Set rectangle size."},
	"shape.rect.set_position":              {Query: "RectNode.SetPosition", Summary: "Set rectangle local position."},
	"shape.rect.set_roundness":             {Query: "RectNode.SetRoundness", Summary: "Set rectangle corner roundness."},
	"shape.ellipse.set_size":               {Query: "EllipseNode.SetSize", Summary: "Set ellipse size."},
	"shape.ellipse.set_position":           {Query: "EllipseNode.SetPosition", Summary: "Set ellipse local position."},
	"shape.star.add":                       {Query: "VectorGroup.AddStar", Summary: "Add a star or polygon shape."},
	"shape.star.set_type":                  {Query: "StarNode.SetStarType", Summary: "Set star or polygon type."},
	"shape.star.set_points":                {Query: "StarNode.SetPoints", Summary: "Set star or polygon point count."},
	"shape.star.set_position":              {Query: "StarNode.SetPosition", Summary: "Set star or polygon position."},
	"shape.star.set_rotation":              {Query: "StarNode.SetRotation", Summary: "Set star or polygon rotation."},
	"shape.star.set_inner_radius":          {Query: "StarNode.SetInnerRadius", Summary: "Set star inner radius."},
	"shape.star.set_outer_radius":          {Query: "StarNode.SetOuterRadius", Summary: "Set star or polygon outer radius."},
	"shape.star.set_inner_roundness":       {Query: "StarNode.SetInnerRoundness", Summary: "Set star inner roundness."},
	"shape.star.set_outer_roundness":       {Query: "StarNode.SetOuterRoundness", Summary: "Set star or polygon outer roundness."},
	"shape.fill.set_color":                 {Query: "FillNode.SetColor", Summary: "Set shape fill color."},
	"shape.fill.set_opacity":               {Query: "FillNode.SetOpacity", Summary: "Set shape fill opacity."},
	"shape.fill.set_blend_mode":            {Query: "FillNode.SetBlendMode", Summary: "Set shape fill blend mode."},
	"shape.fill.set_composite_order":       {Query: "FillNode.SetCompositeOrder", Summary: "Set shape fill composite order."},
	"shape.fill.set_fill_rule":             {Query: "FillNode.SetFillRule", Summary: "Set shape fill rule."},
	"shape.gradient_fill.add":              {Query: "VectorGroup.AddGradientFill", Summary: "Add a gradient fill."},
	"shape.gradient_fill.set_type":         {Query: "GradientFillNode.SetGradientType", Summary: "Set gradient fill type."},
	"shape.gradient_fill.set_start_point":  {Query: "GradientFillNode.SetStartPoint", Summary: "Set gradient fill start point."},
	"shape.gradient_fill.set_end_point":    {Query: "GradientFillNode.SetEndPoint", Summary: "Set gradient fill end point."},
	"shape.gradient_fill.set_highlight_length": {
		Query:   "GradientFillNode.SetHighlightLength",
		Summary: "Set gradient fill highlight length.",
	},
	"shape.gradient_fill.set_highlight_angle": {Query: "GradientFillNode.SetHighlightAngle", Summary: "Set gradient fill highlight angle."},
	"shape.gradient_fill.set_color_stops":     {Query: "GradientFillNode.SetColorStops", Summary: "Set gradient fill color stops."},
	"shape.gradient_fill.set_alpha_stops":     {Query: "GradientFillNode.SetAlphaStops", Summary: "Set gradient fill alpha stops."},
	"shape.gradient_stroke.add":               {Query: "VectorGroup.AddGradientStroke", Summary: "Add a gradient stroke."},
	"shape.gradient_stroke.set_type":          {Query: "GradientStrokeNode.SetGradientType", Summary: "Set gradient stroke type."},
	"shape.gradient_stroke.set_start_point":   {Query: "GradientStrokeNode.SetStartPoint", Summary: "Set gradient stroke start point."},
	"shape.gradient_stroke.set_end_point":     {Query: "GradientStrokeNode.SetEndPoint", Summary: "Set gradient stroke end point."},
	"shape.gradient_stroke.set_highlight_length": {
		Query:   "GradientStrokeNode.SetHighlightLength",
		Summary: "Set gradient stroke highlight length.",
	},
	"shape.gradient_stroke.set_highlight_angle": {Query: "GradientStrokeNode.SetHighlightAngle", Summary: "Set gradient stroke highlight angle."},
	"shape.gradient_stroke.set_width":           {Query: "GradientStrokeNode.SetStrokeWidth", Summary: "Set gradient stroke width."},
	"shape.gradient_stroke.set_line_cap":        {Query: "GradientStrokeNode.SetLineCap", Summary: "Set gradient stroke line cap."},
	"shape.gradient_stroke.set_line_join":       {Query: "GradientStrokeNode.SetLineJoin", Summary: "Set gradient stroke line join."},
	"shape.gradient_stroke.set_miter_limit":     {Query: "GradientStrokeNode.SetMiterLimit", Summary: "Set gradient stroke miter limit."},
	"shape.gradient_stroke.set_color_stops":     {Query: "GradientStrokeNode.SetColorStops", Summary: "Set gradient stroke color stops."},
	"shape.gradient_stroke.set_alpha_stops":     {Query: "GradientStrokeNode.SetAlphaStops", Summary: "Set gradient stroke alpha stops."},
	"shape.stroke.add":                          {Query: "VectorGroup.AddStroke", Summary: "Add a stroke."},
	"shape.stroke.set_color":                    {Query: "StrokeNode.SetColor", Summary: "Set stroke color."},
	"shape.stroke.set_width":                    {Query: "StrokeNode.SetWidth", Summary: "Set stroke width."},
	"shape.stroke.set_opacity":                  {Query: "StrokeNode.SetOpacity", Summary: "Set stroke opacity."},
	"shape.stroke.set_line_cap":                 {Query: "StrokeNode.SetLineCap", Summary: "Set stroke line cap."},
	"shape.stroke.set_line_join":                {Query: "StrokeNode.SetLineJoin", Summary: "Set stroke line join."},
	"shape.stroke.set_miter_limit":              {Query: "StrokeNode.SetMiterLimit", Summary: "Set stroke miter limit."},
	"shape.stroke.set_composite_order":          {Query: "StrokeNode.SetCompositeOrder", Summary: "Set stroke composite order."},
	"shape.stroke_taper.set_start_length":       {Query: "StrokeTaper.SetStartLength", Summary: "Set stroke taper start length."},
	"shape.stroke_taper.set_end_length":         {Query: "StrokeTaper.SetEndLength", Summary: "Set stroke taper end length."},
	"shape.stroke_taper.set_start_width":        {Query: "StrokeTaper.SetStartWidth", Summary: "Set stroke taper start width."},
	"shape.stroke_taper.set_end_width":          {Query: "StrokeTaper.SetEndWidth", Summary: "Set stroke taper end width."},
	"shape.stroke_taper.set_start_ease":         {Query: "StrokeTaper.SetStartEase", Summary: "Set stroke taper start ease."},
	"shape.stroke_taper.set_end_ease":           {Query: "StrokeTaper.SetEndEase", Summary: "Set stroke taper end ease."},
	"shape.stroke_wave.set_amount":              {Query: "StrokeWave.SetAmount", Summary: "Set stroke wave amount."},
	"shape.stroke_wave.set_wavelength":          {Query: "StrokeWave.SetWavelength", Summary: "Set stroke wave wavelength."},
	"shape.stroke_wave.set_phase":               {Query: "StrokeWave.SetPhase", Summary: "Set stroke wave phase."},
	"shape.stroke_dashes.set_dash":              {Query: "StrokeDashes.SetDash", Summary: "Set stroke dash length."},
	"shape.stroke_dashes.set_gap":               {Query: "StrokeDashes.SetGap", Summary: "Set stroke gap length."},
	"shape.trim.add":                            {Query: "VectorGroup.AddTrim", Summary: "Add Trim Paths."},
	"shape.round_corners.add":                   {Query: "VectorGroup.AddRoundCorners", Summary: "Add Round Corners."},
	"shape.round_corners.set_radius":            {Query: "RoundCornersNode.SetRadius", Summary: "Set Round Corners radius."},
	"shape.offset_paths.add":                    {Query: "VectorGroup.AddOffsetPaths", Summary: "Add Offset Paths."},
	"shape.offset_paths.set_amount":             {Query: "OffsetPathsNode.SetAmount", Summary: "Set Offset Paths amount."},
	"shape.offset_paths.set_line_join":          {Query: "OffsetPathsNode.SetLineJoin", Summary: "Set Offset Paths line join."},
	"shape.offset_paths.set_miter_limit":        {Query: "OffsetPathsNode.SetMiterLimit", Summary: "Set Offset Paths miter limit."},
	"shape.offset_paths.set_copies":             {Query: "OffsetPathsNode.SetCopies", Summary: "Set Offset Paths copies."},
	"shape.offset_paths.set_copy_offset":        {Query: "OffsetPathsNode.SetCopyOffset", Summary: "Set Offset Paths copy offset."},
	"shape.repeater.add":                        {Query: "VectorGroup.AddRepeater", Summary: "Add Repeater."},
	"shape.repeater.set_copies":                 {Query: "RepeaterNode.SetCopies", Summary: "Set Repeater copies."},
	"shape.repeater.set_offset":                 {Query: "RepeaterNode.SetOffset", Summary: "Set Repeater offset."},
	"shape.repeater.set_order":                  {Query: "RepeaterNode.SetOrder", Summary: "Set Repeater order."},
	"shape.repeater_transform.set_anchor":       {Query: "RepeaterTransform.SetAnchor", Summary: "Set Repeater transform anchor."},
	"shape.repeater_transform.set_position":     {Query: "RepeaterTransform.SetPosition", Summary: "Set Repeater transform position."},
	"shape.repeater_transform.set_scale":        {Query: "RepeaterTransform.SetScale", Summary: "Set Repeater transform scale."},
	"shape.repeater_transform.set_rotation":     {Query: "RepeaterTransform.SetRotation", Summary: "Set Repeater transform rotation."},
	"shape.repeater_transform.set_start_opacity": {
		Query:   "RepeaterTransform.SetStartOpacity",
		Summary: "Set Repeater transform start opacity.",
	},
	"shape.repeater_transform.set_end_opacity": {Query: "RepeaterTransform.SetEndOpacity", Summary: "Set Repeater transform end opacity."},
	"shape.merge_paths.add":                    {Query: "VectorGroup.AddMergePaths", Summary: "Add Merge Paths."},
	"shape.merge_paths.set_type":               {Query: "MergePathsNode.SetType", Summary: "Set Merge Paths type."},
	"shape.zigzag.add":                         {Query: "VectorGroup.AddZigZag", Summary: "Add Zig Zag."},
	"shape.zigzag.set_size":                    {Query: "ZigZagNode.SetSize", Summary: "Set Zig Zag size."},
	"shape.zigzag.set_detail":                  {Query: "ZigZagNode.SetDetail", Summary: "Set Zig Zag detail."},
	"shape.zigzag.set_points":                  {Query: "ZigZagNode.SetPoints", Summary: "Set Zig Zag points mode."},
	"shape.pucker_bloat.add":                   {Query: "VectorGroup.AddPuckerBloat", Summary: "Add Pucker and Bloat."},
	"shape.pucker_bloat.set_amount":            {Query: "PuckerBloatNode.SetAmount", Summary: "Set Pucker and Bloat amount."},
	"shape.twist.add":                          {Query: "VectorGroup.AddTwist", Summary: "Add Twist."},
	"shape.twist.set_angle":                    {Query: "TwistNode.SetAngle", Summary: "Set Twist angle."},
	"shape.twist.set_center":                   {Query: "TwistNode.SetCenter", Summary: "Set Twist center."},
	"shape.wiggle_paths.add":                   {Query: "VectorGroup.AddWigglePaths", Summary: "Add Wiggle Paths."},
	"shape.wiggle_paths.set_size":              {Query: "WigglePathsNode.SetSize", Summary: "Set Wiggle Paths size."},
	"shape.wiggle_paths.set_detail":            {Query: "WigglePathsNode.SetDetail", Summary: "Set Wiggle Paths detail."},
	"shape.wiggle_paths.set_wiggles_per_second": {
		Query:   "WigglePathsNode.SetWigglesPerSecond",
		Summary: "Set Wiggle Paths wiggles per second.",
	},
	"shape.wiggle_paths.set_random_seed":    {Query: "WigglePathsNode.SetRandomSeed", Summary: "Set Wiggle Paths random seed."},
	"shape.wiggle_paths.set_points":         {Query: "WigglePathsNode.SetPoints", Summary: "Set Wiggle Paths points mode."},
	"shape.wiggle_paths.set_correlation":    {Query: "WigglePathsNode.SetCorrelation", Summary: "Set Wiggle Paths correlation."},
	"shape.wiggle_paths.set_temporal_phase": {Query: "WigglePathsNode.SetTemporalPhase", Summary: "Set Wiggle Paths temporal phase."},
	"shape.wiggle_paths.set_spatial_phase":  {Query: "WigglePathsNode.SetSpatialPhase", Summary: "Set Wiggle Paths spatial phase."},
	"shape.wiggle_transform.add":            {Query: "VectorGroup.AddWiggleTransform", Summary: "Add Wiggle Transform."},
	"shape.wiggler_transform.set_anchor":    {Query: "WigglerTransform.SetAnchor", Summary: "Set Wiggle Transform anchor."},
	"shape.wiggler_transform.set_position":  {Query: "WigglerTransform.SetPosition", Summary: "Set Wiggle Transform position."},
	"shape.wiggler_transform.set_scale":     {Query: "WigglerTransform.SetScale", Summary: "Set Wiggle Transform scale."},
	"shape.wiggler_transform.set_rotation":  {Query: "WigglerTransform.SetRotation", Summary: "Set Wiggle Transform rotation."},
	"shape.wiggle_transform.set_wiggles_per_second": {
		Query:   "WiggleTransformNode.SetWigglesPerSecond",
		Summary: "Set Wiggle Transform wiggles per second.",
	},
	"shape.wiggle_transform.set_random_seed":    {Query: "WiggleTransformNode.SetRandomSeed", Summary: "Set Wiggle Transform random seed."},
	"shape.wiggle_transform.set_correlation":    {Query: "WiggleTransformNode.SetCorrelation", Summary: "Set Wiggle Transform correlation."},
	"shape.wiggle_transform.set_temporal_phase": {Query: "WiggleTransformNode.SetTemporalPhase", Summary: "Set Wiggle Transform temporal phase."},
	"shape.wiggle_transform.set_spatial_phase":  {Query: "WiggleTransformNode.SetSpatialPhase", Summary: "Set Wiggle Transform spatial phase."},
	"mask.add":                        {Query: "AddMask", Summary: "Add a vector mask to a layer."},
	"mask.set_mode":                   {Query: "Mask.SetMode", Summary: "Set mask blend mode."},
	"mask.set_inverted":               {Query: "Mask.SetInverted", Summary: "Set mask inverted switch."},
	"mask.set_locked":                 {Query: "Mask.SetLocked", Summary: "Set mask lock switch."},
	"mask.set_color":                  {Query: "Mask.SetColor", Summary: "Set mask timeline color."},
	"mask.set_motion_blur":            {Query: "Mask.SetMaskMotionBlur", Summary: "Set mask motion blur override."},
	"mask.set_feather_falloff":        {Query: "Mask.SetFeatherFalloff", Summary: "Set mask feather falloff curve."},
	"mask.set_opacity":                {Query: "Mask.SetOpacity", Summary: "Set mask opacity."},
	"mask.set_feather":                {Query: "Mask.SetFeather", Summary: "Set mask feather vector."},
	"mask.set_expansion":              {Query: "Mask.SetExpansion", Summary: "Set mask expansion."},
	"mask.set_path_keyframes":         {Query: "SetMaskPathKeyframes", Summary: "Set animated mask path keyframes."},
	"effect.add_builtin":              {Query: "AddEffect", Summary: "Add a supported built-in effect."},
	"effect.set_param":                {Query: "SetEffectParam", Summary: "Set an effect parameter value."},
	"property.set_expression":         {Query: "Property.SetExpression", Summary: "Set a property expression."},
	"property.set_expression_enabled": {Query: "Property.SetExpressionEnabled", Summary: "Toggle property expression evaluation."},
}
