package recipedoc

var capabilitiesByPath = map[string][]string{
	"comps[]":                                                     {"comp.create"},
	"comps[].background_color":                                    {"comp.set_background_color"},
	"comps[].label":                                               {"comp.set_label"},
	"comps[].comment":                                             {"comp.set_comment"},
	"comps[].renderer":                                            {"comp.set_renderer"},
	"comps[].resolution_factor":                                   {"comp.set_resolution_factor"},
	"comps[].pixel_aspect":                                        {"comp.set_pixel_aspect"},
	"comps[].display_start_time":                                  {"comp.set_display_start_time"},
	"comps[].frame_blending":                                      {"comp.set_frame_blending"},
	"comps[].draft_3d":                                            {"comp.set_draft_3d"},
	"comps[].hide_shy_layers":                                     {"comp.set_hide_shy_layers"},
	"comps[].preserve_nested_frame_rate":                          {"comp.set_preserve_nested_frame_rate"},
	"comps[].preserve_nested_resolution":                          {"comp.set_preserve_nested_resolution"},
	"comps[].motion_blur.enabled":                                 {"comp.set_motion_blur"},
	"comps[].motion_blur.shutter_angle":                           {"comp.set_motion_blur_shutter_angle"},
	"comps[].motion_blur.shutter_phase":                           {"comp.set_motion_blur_shutter_phase"},
	"comps[].motion_blur.adaptive_sample_limit":                   {"comp.set_motion_blur_adaptive_sample_limit"},
	"comps[].motion_blur.samples_per_frame":                       {"comp.set_motion_blur_samples_per_frame"},
	"comps[].work_area":                                           {"comp.set_work_area"},
	"comps[].work_area.start":                                     {"comp.set_work_area"},
	"comps[].work_area.end":                                       {"comp.set_work_area"},
	"comps[].layers[].type":                                       {"layer.create_text", "layer.create_shape", "layer.create_solid", "layer.create_camera", "layer.create_light", "layer.create_null", "layer.create_adjustment"},
	"comps[].layers[].label":                                      {"layer.set_label"},
	"comps[].layers[].comment":                                    {"layer.set_comment"},
	"comps[].layers[].visible":                                    {"layer.set_visible"},
	"comps[].layers[].solo":                                       {"layer.set_solo"},
	"comps[].layers[].locked":                                     {"layer.set_locked"},
	"comps[].layers[].motion_blur":                                {"layer.set_motion_blur"},
	"comps[].layers[].shy":                                        {"layer.set_shy"},
	"comps[].layers[].effects_enabled":                            {"layer.set_effects_enabled"},
	"comps[].layers[].audio_enabled":                              {"layer.set_audio_enabled"},
	"comps[].layers[].frame_blend_enabled":                        {"layer.set_frame_blend_enabled"},
	"comps[].layers[].markers_locked":                             {"layer.set_markers_locked"},
	"comps[].layers[].collapse_transform":                         {"layer.set_collapse_transform"},
	"comps[].layers[].is_3d":                                      {"layer.set_is_3d"},
	"comps[].layers[].is_adjust":                                  {"layer.set_is_adjust"},
	"comps[].layers[].is_null":                                    {"layer.set_is_null"},
	"comps[].layers[].is_guide":                                   {"layer.set_is_guide"},
	"comps[].layers[].sampling_bicubic":                           {"layer.set_sampling_bicubic"},
	"comps[].layers[].frame_blend_pixel_motion":                   {"layer.set_frame_blend_pixel_motion"},
	"comps[].layers[].preserve_transparency":                      {"layer.set_preserve_transparency"},
	"comps[].layers[].quality":                                    {"layer.set_quality"},
	"comps[].layers[].blending_mode":                              {"layer.set_blending_mode"},
	"comps[].layers[].track_matte":                                {"layer.set_track_matte"},
	"comps[].layers[].auto_orient":                                {"layer.set_auto_orient"},
	"comps[].layers[].start_time":                                 {"layer.set_start_time"},
	"comps[].layers[].in_point":                                   {"layer.set_in_point"},
	"comps[].layers[].out_point":                                  {"layer.set_out_point"},
	"comps[].layers[].parent":                                     {"layer.set_parent"},
	"comps[].layers[].text":                                       {"layer.set_text"},
	"comps[].layers[].text_style.font_size":                       {"text.set_run_font_size"},
	"comps[].layers[].text_style.fill_color":                      {"text.set_run_fill_color"},
	"comps[].layers[].text_style.tracking":                        {"text.set_run_tracking"},
	"comps[].layers[].text_style.faux_bold":                       {"text.set_run_faux_bold"},
	"comps[].layers[].text_style.faux_italic":                     {"text.set_run_faux_italic"},
	"comps[].layers[].text_style.apply_stroke":                    {"text.set_run_apply_stroke"},
	"comps[].layers[].text_style.stroke_color":                    {"text.set_run_stroke_color"},
	"comps[].layers[].text_style.stroke_width":                    {"text.set_run_stroke_width"},
	"comps[].layers[].text_style.justification":                   {"text.set_paragraph_justification"},
	"comps[].layers[].camera.zoom":                                {"camera.set_zoom"},
	"comps[].layers[].camera.depth_of_field":                      {"camera.set_depth_of_field"},
	"comps[].layers[].camera.focus_distance":                      {"camera.set_focus_distance"},
	"comps[].layers[].camera.aperture":                            {"camera.set_aperture"},
	"comps[].layers[].camera.blur_level":                          {"camera.set_blur_level"},
	"comps[].layers[].camera.iris_shape":                          {"camera.set_iris_shape"},
	"comps[].layers[].camera.iris_rotation":                       {"camera.set_iris_rotation"},
	"comps[].layers[].camera.iris_roundness":                      {"camera.set_iris_roundness"},
	"comps[].layers[].camera.iris_aspect_ratio":                   {"camera.set_iris_aspect_ratio"},
	"comps[].layers[].camera.iris_diffraction_fringe":             {"camera.set_iris_diffraction_fringe"},
	"comps[].layers[].camera.iris_highlight_gain":                 {"camera.set_iris_highlight_gain"},
	"comps[].layers[].camera.iris_highlight_threshold":            {"camera.set_iris_highlight_threshold"},
	"comps[].layers[].camera.iris_highlight_saturation":           {"camera.set_iris_highlight_saturation"},
	"comps[].layers[].light.kind":                                 {"light.set_kind"},
	"comps[].layers[].light.source_layer":                         {"light.set_source_layer"},
	"comps[].layers[].light.intensity":                            {"light.set_intensity"},
	"comps[].layers[].light.color":                                {"light.set_color"},
	"comps[].layers[].light.casts_shadows":                        {"light.set_casts_shadows"},
	"comps[].layers[].light.shadow_darkness":                      {"light.set_shadow_darkness"},
	"comps[].layers[].light.shadow_diffusion":                     {"light.set_shadow_diffusion"},
	"comps[].layers[].light.falloff_type":                         {"light.set_falloff_type"},
	"comps[].layers[].light.falloff_start":                        {"light.set_falloff_start"},
	"comps[].layers[].light.falloff_distance":                     {"light.set_falloff_distance"},
	"comps[].layers[].light.cone_angle":                           {"light.set_cone_angle"},
	"comps[].layers[].light.cone_feather":                         {"light.set_cone_feather"},
	"comps[].layers[].transform":                                  {"layer.set_transform"},
	"comps[].layers[].effects[]":                                  {"effect.add_builtin"},
	"comps[].layers[].effects[].params[]":                         {"effect.set_param"},
	"comps[].layers[].effects[].params[].expression.source":       {"property.set_expression"},
	"comps[].layers[].transform.expressions.position.source":      {"property.set_expression"},
	"comps[].layers[].transform.expressions.anchor_point.source":  {"property.set_expression"},
	"comps[].layers[].transform.expressions.scale.source":         {"property.set_expression"},
	"comps[].layers[].transform.expressions.rotation.source":      {"property.set_expression"},
	"comps[].layers[].transform.expressions.opacity.source":       {"property.set_expression"},
	"comps[].layers[].transform.expressions.position.enabled":     {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.anchor_point.enabled": {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.scale.enabled":        {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.rotation.enabled":     {"property.set_expression_enabled"},
	"comps[].layers[].transform.expressions.opacity.enabled":      {"property.set_expression_enabled"},
	"comps[].layers[].effects[].params[].expression.enabled":      {"property.set_expression_enabled"},
}

var capabilityRegistry = map[string]CapabilityMeta{
	"comp.create":                 {Query: "NewComposition", Summary: "Create a composition."},
	"comp.set_background_color":   {Query: "Composition.SetBGColor", Summary: "Set composition background color."},
	"comp.set_label":              {Query: "Composition.SetLabel", Summary: "Set composition label color."},
	"comp.set_comment":            {Query: "Composition.SetComment", Summary: "Set composition comment."},
	"comp.set_renderer":           {Query: "SetRenderer", Summary: "Set composition renderer."},
	"comp.set_resolution_factor":  {Query: "Composition.SetResolutionFactor", Summary: "Set composition preview resolution factor."},
	"comp.set_pixel_aspect":       {Query: "Composition.SetPixelAspect", Summary: "Set composition pixel aspect ratio."},
	"comp.set_display_start_time": {Query: "Composition.SetDisplayStartTime", Summary: "Set composition display start time."},
	"comp.set_frame_blending":     {Query: "Composition.SetFrameBlending", Summary: "Set composition frame blending."},
	"comp.set_draft_3d":           {Query: "Composition.SetDraft3D", Summary: "Set composition draft 3D switch."},
	"comp.set_hide_shy_layers":    {Query: "Composition.SetHideShyLayers", Summary: "Set composition shy-layer visibility."},
	"comp.set_preserve_nested_frame_rate": {
		Query:   "Composition.SetPreserveNestedFrameRate",
		Summary: "Set nested frame-rate preservation.",
	},
	"comp.set_preserve_nested_resolution": {
		Query:   "Composition.SetPreserveNestedResolution",
		Summary: "Set nested resolution preservation.",
	},
	"comp.set_motion_blur":                       {Query: "Composition.SetCompMotionBlur", Summary: "Set composition motion blur."},
	"comp.set_motion_blur_shutter_angle":         {Query: "Composition.SetShutterAngle", Summary: "Set composition shutter angle."},
	"comp.set_motion_blur_shutter_phase":         {Query: "Composition.SetShutterPhase", Summary: "Set composition shutter phase."},
	"comp.set_motion_blur_adaptive_sample_limit": {Query: "Composition.SetMotionBlurAdaptiveSampleLimit", Summary: "Set motion blur adaptive sample limit."},
	"comp.set_motion_blur_samples_per_frame":     {Query: "Composition.SetMotionBlurSamplesPerFrame", Summary: "Set motion blur samples per frame."},
	"comp.set_work_area":                         {Query: "Composition.SetWorkArea", Summary: "Set composition work area."},
	"layer.create_text":                          {Query: "NewTextLayer", Summary: "Create a text layer."},
	"layer.create_shape":                         {Query: "NewShapeLayer", Summary: "Create a shape layer."},
	"layer.create_solid":                         {Query: "NewSolidLayer", Summary: "Create a solid layer."},
	"layer.create_camera":                        {Query: "NewCameraLayer", Summary: "Create a camera layer."},
	"layer.create_light":                         {Query: "NewLightLayer", Summary: "Create a light layer."},
	"layer.create_null":                          {Query: "NewNullLayer", Summary: "Create a null layer."},
	"layer.create_adjustment":                    {Query: "NewAdjustmentLayer", Summary: "Create an adjustment layer."},
	"layer.set_label":                            {Query: "Layer.SetLabel", Summary: "Set layer label color."},
	"layer.set_comment":                          {Query: "Layer.SetComment", Summary: "Set layer comment."},
	"layer.set_visible":                          {Query: "Layer.SetVisible", Summary: "Set layer visibility."},
	"layer.set_solo":                             {Query: "Layer.SetSolo", Summary: "Set layer solo switch."},
	"layer.set_locked":                           {Query: "Layer.SetLocked", Summary: "Set layer lock switch."},
	"layer.set_motion_blur":                      {Query: "Layer.SetMotionBlur", Summary: "Set layer motion blur."},
	"layer.set_shy":                              {Query: "Layer.SetShy", Summary: "Set layer shy switch."},
	"layer.set_effects_enabled":                  {Query: "Layer.SetEffectsEnabled", Summary: "Set layer effects switch."},
	"layer.set_audio_enabled":                    {Query: "Layer.SetAudioEnabled", Summary: "Set layer audio switch."},
	"layer.set_frame_blend_enabled":              {Query: "Layer.SetFrameBlendEnabled", Summary: "Set layer frame blending."},
	"layer.set_markers_locked":                   {Query: "Layer.SetMarkersLocked", Summary: "Set layer marker lock switch."},
	"layer.set_collapse_transform":               {Query: "Layer.SetCollapseTransform", Summary: "Set collapse transformations."},
	"layer.set_is_3d":                            {Query: "Layer.SetIs3D", Summary: "Set layer 3D switch."},
	"layer.set_is_adjust":                        {Query: "Layer.SetIsAdjust", Summary: "Set adjustment-layer switch."},
	"layer.set_is_null":                          {Query: "Layer.SetIsNull", Summary: "Set null-layer switch."},
	"layer.set_is_guide":                         {Query: "Layer.SetIsGuide", Summary: "Set guide-layer switch."},
	"layer.set_sampling_bicubic":                 {Query: "Layer.SetSamplingBicubic", Summary: "Set bicubic sampling switch."},
	"layer.set_frame_blend_pixel_motion": {
		Query:   "Layer.SetFrameBlendPixelMotion",
		Summary: "Set pixel-motion frame blending.",
	},
	"layer.set_preserve_transparency": {Query: "Layer.SetPreserveTransparency", Summary: "Set preserve transparency switch."},
	"layer.set_quality":               {Query: "Layer.SetQuality", Summary: "Set layer quality mode."},
	"layer.set_blending_mode":         {Query: "Layer.SetBlendingMode", Summary: "Set layer blending mode."},
	"layer.set_track_matte":           {Query: "Layer.SetTrackMatte", Summary: "Set layer track matte."},
	"layer.set_auto_orient":           {Query: "Layer.SetAutoOrient", Summary: "Set layer auto orientation."},
	"layer.set_start_time":            {Query: "Layer.SetStartTime", Summary: "Set layer start time."},
	"layer.set_in_point":              {Query: "Layer.SetInPoint", Summary: "Set layer in point."},
	"layer.set_out_point":             {Query: "Layer.SetOutPoint", Summary: "Set layer out point."},
	"layer.set_parent":                {Query: "Layer.SetParent", Summary: "Set layer parent."},
	"layer.set_text":                  {Query: "Layer.SetText", Summary: "Set text layer source text."},
	"layer.set_transform":             {Query: "SetLayerTransform", Summary: "Set layer transform values."},
	"text.set_run_font_size":          {Query: "Layer.SetRunFontSize", Summary: "Set text run font size."},
	"text.set_run_fill_color":         {Query: "Layer.SetRunFillColor", Summary: "Set text run fill color."},
	"text.set_run_tracking":           {Query: "Layer.SetRunTracking", Summary: "Set text run tracking."},
	"text.set_run_faux_bold":          {Query: "Layer.SetRunFauxBold", Summary: "Set text run faux bold."},
	"text.set_run_faux_italic":        {Query: "Layer.SetRunFauxItalic", Summary: "Set text run faux italic."},
	"text.set_run_apply_stroke":       {Query: "Layer.SetRunApplyStroke", Summary: "Set text run stroke enable switch."},
	"text.set_run_stroke_color":       {Query: "Layer.SetRunStrokeColor", Summary: "Set text run stroke color."},
	"text.set_run_stroke_width":       {Query: "Layer.SetRunStrokeWidth", Summary: "Set text run stroke width."},
	"text.set_paragraph_justification": {
		Query:   "Layer.SetParagraphJustification",
		Summary: "Set paragraph justification.",
	},
	"camera.set_zoom":                      {Query: "Layer.SetCameraZoom", Summary: "Set camera zoom."},
	"camera.set_depth_of_field":            {Query: "Layer.SetCameraDepthOfField", Summary: "Set camera depth of field."},
	"camera.set_focus_distance":            {Query: "Layer.SetCameraFocusDistance", Summary: "Set camera focus distance."},
	"camera.set_aperture":                  {Query: "Layer.SetCameraAperture", Summary: "Set camera aperture."},
	"camera.set_blur_level":                {Query: "Layer.SetCameraBlurLevel", Summary: "Set camera blur level."},
	"camera.set_iris_shape":                {Query: "Layer.SetIrisShape", Summary: "Set camera iris shape."},
	"camera.set_iris_rotation":             {Query: "Layer.SetIrisRotation", Summary: "Set camera iris rotation."},
	"camera.set_iris_roundness":            {Query: "Layer.SetIrisRoundness", Summary: "Set camera iris roundness."},
	"camera.set_iris_aspect_ratio":         {Query: "Layer.SetIrisAspectRatio", Summary: "Set camera iris aspect ratio."},
	"camera.set_iris_diffraction_fringe":   {Query: "Layer.SetIrisDiffractionFringe", Summary: "Set camera iris diffraction fringe."},
	"camera.set_iris_highlight_gain":       {Query: "Layer.SetIrisHighlightGain", Summary: "Set camera iris highlight gain."},
	"camera.set_iris_highlight_threshold":  {Query: "Layer.SetIrisHighlightThreshold", Summary: "Set camera iris highlight threshold."},
	"camera.set_iris_highlight_saturation": {Query: "Layer.SetIrisHighlightSaturation", Summary: "Set camera iris highlight saturation."},
	"light.set_kind":                       {Query: "Layer.SetLightKind", Summary: "Set light kind."},
	"light.set_source_layer":               {Query: "Layer.SetLightSource", Summary: "Set light source layer."},
	"light.set_intensity":                  {Query: "Layer.SetLightIntensity", Summary: "Set light intensity."},
	"light.set_color":                      {Query: "Layer.SetLightColor", Summary: "Set light color."},
	"light.set_casts_shadows":              {Query: "Layer.SetLightCastsShadows", Summary: "Set light shadow-casting switch."},
	"light.set_shadow_darkness":            {Query: "Layer.SetLightShadowDarkness", Summary: "Set light shadow darkness."},
	"light.set_shadow_diffusion":           {Query: "Layer.SetLightShadowDiffusion", Summary: "Set light shadow diffusion."},
	"light.set_falloff_type":               {Query: "Layer.SetLightFalloffType", Summary: "Set light falloff type."},
	"light.set_falloff_start":              {Query: "Layer.SetLightFalloffStart", Summary: "Set light falloff start."},
	"light.set_falloff_distance":           {Query: "Layer.SetLightFalloffDistance", Summary: "Set light falloff distance."},
	"light.set_cone_angle":                 {Query: "Layer.SetLightConeAngle", Summary: "Set spotlight cone angle."},
	"light.set_cone_feather":               {Query: "Layer.SetLightConeFeather", Summary: "Set spotlight cone feather."},
	"effect.add_builtin":                   {Query: "AddEffect", Summary: "Add a supported built-in effect."},
	"effect.set_param":                     {Query: "SetEffectParam", Summary: "Set an effect parameter value."},
	"property.set_expression":              {Query: "Property.SetExpression", Summary: "Set a property expression."},
	"property.set_expression_enabled":      {Query: "Property.SetExpressionEnabled", Summary: "Toggle property expression evaluation."},
}
