package recipedoc

import (
	"fmt"
	"strings"
)

func RenderMarkdown(doc Document) string {
	var b strings.Builder
	b.WriteString("# Recipe Field Reference\n\n")
	b.WriteString("<!-- Code generated by recipedocgen; DO NOT EDIT. -->\n\n")
	b.WriteString("This reference is generated from the canonical recipe field model.\n\n")

	groups := map[string][]FieldModel{}
	var order []string
	for _, field := range doc.Fields {
		if _, ok := groups[field.SourceType]; !ok {
			order = append(order, field.SourceType)
		}
		groups[field.SourceType] = append(groups[field.SourceType], field)
	}
	for _, sourceType := range order {
		fmt.Fprintf(&b, "## %s\n\n", sourceType)
		b.WriteString("| Field Path | Type | Requiredness | Summary | Validation | Capability |\n")
		b.WriteString("| --- | --- | --- | --- | --- | --- |\n")
		for _, field := range groups[sourceType] {
			fmt.Fprintf(
				&b,
				"| `%s` | `%s` | %s | %s | %s | %s |\n",
				escapeMD(field.Path),
				escapeMD(typeLabel(field.Type)),
				escapeMD(requirednessLabel(field)),
				escapeMD(summaryLabel(field)),
				escapeMD(emptyDash(field.Validation)),
				escapeMD(capabilityLabel(field.Capabilities)),
			)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func typeLabel(ref TypeRef) string {
	if ref.Kind == "array" && ref.Element != "" {
		return ref.Kind + "<" + ref.Element + ">"
	}
	if ref.ObjectType != "" {
		return ref.Kind + "<" + ref.ObjectType + ">"
	}
	return ref.Kind
}

func requirednessLabel(field FieldModel) string {
	var labels []string
	if field.StructuralRequired {
		labels = append(labels, "structural")
	}
	if field.ValidationRequired {
		labels = append(labels, "validation")
	}
	if len(labels) == 0 {
		return "-"
	}
	return strings.Join(labels, ", ")
}

func summaryLabel(field FieldModel) string {
	if field.MissingSemanticSummary {
		return "missing semantic summary"
	}
	return emptyDash(field.Summary)
}

func capabilityLabel(caps []CapabilityRef) string {
	if len(caps) == 0 {
		return "-"
	}
	parts := make([]string, 0, len(caps))
	for _, cap := range caps {
		label := "`" + cap.Key + "`"
		if cap.Query != "" {
			label += " (`" + cap.Query + "`)"
		}
		parts = append(parts, label)
	}
	return strings.Join(parts, "<br>")
}

func emptyDash(value string) string {
	if value == "" {
		return "-"
	}
	return value
}

func escapeMD(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", "\\|")
	return value
}
